### PR TITLE
Upgrade config/*/tests from medic-nootils/test-wrapper to medic-conf-test-harness

### PR DESCRIPTION
**Pull request by kennsippell**
# Description

Medic-nootils@4.x deletes the test-wrapper library https://github.com/medic/medic-nootils/pull/13

To ensure that we can bump medic-nootils to the latest version in the cht-core repository, this change updates `config/standard` and `config/sample_config_tests` to use the medic-conf-test-harness. 

An unnecessary dependency on medic-nootils declared by `config/default` is removed.

https://github.com/medic/medic-nootils/issues/9

# Code review items

- Readable: Concise, well named, follows the [style guide](https://github.com/medic/medic-docs/blob/master/development/style-guide.md), documented if necessary.
- Documented: Configuration and user documentation on [medic-docs](https://github.com/medic/medic-docs/)
- Tested: Unit and/or e2e where appropriate
- Internationalised: All user facing text
- Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in Changes.md.

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

### CODE REVIEW

**Comment by kennsippell** [comment]
I'm unsure how much value the config/sample_config_tests project is providing since there are example tests as part of the test harness documentation and we have some additional training resources in the pipe.  These aren't particularly good examples, and I find it easier to maintain the examples within the harness repo rather than this external example. 

Could we consider removing this? @garethbowen  https://htmlpreview.github.io/?https://raw.githubusercontent.com/medic/medic-conf-test-harness/blob/master/out/index.html

**Comment by kennsippell** [comment]
Discussed removal of sample_config_tests today with @abbyad. It seems these are safe to remove now since the tests for the CHT reference app are now our sample configuration tests.

**Comment by kennsippell** [comment]
@wtekeu Thanks for reviewing Willy! Can you approve the review if this looks good to you? I'm having trouble finding this function that you wrote -- what file was that in?

```
  function daysAgo(n) {
    const d = new Date(today);
    d.setDate(d.getDate() - n);
    return d.getTime();
  }
```

**Comment by wtekeu** [comment]
it is in both `targets.spec.js` and `tasks.spec.js` (bottom of the file)

**Comment by kennsippell** [comment]
This is great feedback. But I'd like to scope this to making test-only changes only here. 
@binokaryg would you note Willy's feedback above?

**Comment by binokaryg** [comment]
Thanks, noted the suggestions on the standard tests.
Just removing `today` or `now` from these lines caused some more tests to fail.
- `const d = new Date(today);` in [targets.spec.js](https://github.com/medic/cht-core/blob/4ce8891df49c2ad90e950530b007ca707fce6713/config/standard/test/targets.spec.js#L2483)
- ` const d = new Date(now);` in [tasks.spec.js](https://github.com/medic/cht-core/blob/4ce8891df49c2ad90e950530b007ca707fce6713/config/standard/test/tasks.spec.js#L729)

This is because of the variables such as `threeWeeksAgo` being assigned before sinon's fakeTimers take effect. It should work fine if we use functions instead. Shall I create another PR fixing these?
Also, noticed that 24 other tests in `tasks.spec.js` are failing regardless of this change.

**Pull request merged**
