### PR TITLE
chore: Add logic to fill up a report form that generates a task using the settings file

### PR DESCRIPTION
**Pull request by ralfudx**
# Description

Please see full description in [#108](https://github.com/medic/care-teams/issues/108)

To review this you can do the following:
- Check the files changed and ensure there's nothing strange/out of place
- Pull the latest from the main branch and checkout this `fill-up-report-form-and-navigation-tests` branch
- Run npm ci from the repository's root directory
- Use the `SAMPLE-#108-apdex-settings-kenya-with-forms.json` file from the [Apdex Automation settings files](https://drive.google.com/drive/folders/1ZD5UhVmofw3amiYslpHg-xgeD-0QaoB6) drive
- Connect your mobile device and then run `npm run apdex-test`
- All the tests should run on the physical device successfully.

# Code review checklist

- [ ] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- [ ] Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- [ ] Tested: Unit and/or e2e where appropriate
- [ ] Internationalised: All user facing text
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# Compose URLs
If Build CI hasn't passed, these may 404:

* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:fill-up-report-form-and-navigation-tests/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:fill-up-report-form-and-navigation-tests/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:fill-up-report-form-and-navigation-tests/docker-compose/cht-couchdb-clustered.yml)

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

### CODE REVIEW

**Comment by ralfudx** [comment]
@Benmuiruri and @lorerod kindly have a look at this when you have some time - thanks in advance

**Review by Benmuiruri — COMMENTED** [review]
Hi @ralfudx the script runs and submits the SGBV Report just fine, but that does not trigger a Task. 

I have even submitted an SGBV Report manually, even that did not trigger a task.

**Review by lorerod — COMMENTED** [review]
Hi, @ralfudx; I ran this using the https://care-teams-4x.dev.medicmobile.org/ instance and the config you shared. 
But, I had to scroll manually several times for the test to find the elements. And not all the tests passed. This was the results:
```
s/performance/apdex-score/apk/CHTAndroid.apk Android #0-0] » /tests/performance/apdex-score/test/specs/num-1/test.apdex.js
[tests/performance/apdex-score/apk/CHTAndroid.apk Android #0-0] Apdex Performance Workflows
[tests/performance/apdex-score/apk/CHTAndroid.apk Android #0-0]    ✓ should load contact list
[tests/performance/apdex-score/apk/CHTAndroid.apk Android #0-0]    ✓ should load CHW area
[tests/performance/apdex-score/apk/CHTAndroid.apk Android #0-0]    ✖ should load Household
[tests/performance/apdex-score/apk/CHTAndroid.apk Android #0-0]    ✓ should load patient
[tests/performance/apdex-score/apk/CHTAndroid.apk Android #0-0]    ✖ should submit patient report
[tests/performance/apdex-score/apk/CHTAndroid.apk Android #0-0]    ✖ should create patient
[tests/performance/apdex-score/apk/CHTAndroid.apk Android #0-0]    ✖ should load message list and view a message
[tests/performance/apdex-score/apk/CHTAndroid.apk Android #0-0]    ✖ should load task list and view a task
[tests/performance/apdex-score/apk/CHTAndroid.apk Android #0-0]    ✖ should load report list and view a report
[tests/performance/apdex-score/apk/CHTAndroid.apk Android #0-0]    ✖ should load analytics and relaunch the app
[tests/performance/apdex-score/apk/CHTAndroid.apk Android #0-0]
[tests/performance/apdex-score/apk/CHTAndroid.apk Android #0-0] 3 passing (2h 26m 9.8s)
[tests/performance/apdex-score/apk/CHTAndroid.apk Android #0-0] 7 failing

```
Another important thing is that I couldn't run this locally; having a config that runs well with the cht local setup may be a good idea.

**Comment by ralfudx** [comment]
Hi @lorerod thank you for testing this and providing your feedback. 
For the behaviour you are experiencing, it appears some of the validation elements have changed position on the screen so you need to add the relevant number of scrolls and also modify the validation elements (if they have changed) on the `settings.json` file as these can change with dates and also when we run tests that create new patients for the same household multiple times - like the `should create patient` test
You may also need to know how to use the `settings.json` file in order to get this working without any hassle - if you need a quick sync on this, kindly let me know.

Also, regarding the important thing you mentioned about running the tests with a `cht local set-up` - the same thing applies for this as well - each one of these tests can be executed successfully on any config - you'd just need to adjust the settings.json file to match the elements displayed and configured for that local instance

Here's my result after adjusting the `settings.json` file - and I didn't have to scroll manually for this to work
I have sent you this modified settings file on Slack
Screenshot 2024-06-04 at 09 19 05

**Comment by ralfudx** [comment]
FYI @Benmuiruri @lorerod I have now merged the [PR for user search scenario](https://github.com/medic/cht-core/pull/9152) into this one and modified the order of the tests - so we should now have a total of 11 tests running

**Comment by lorerod** [comment]
thanks @ralfudx !
I was able to run it successfully.
```
[tests/performance/apdex-score/apk/CHTAndroid.apk Android #0-0] Session ID: b8ee9885-59ee-40ac-8790-85e3a5ec57a6
[tests/performance/apdex-score/apk/CHTAndroid.apk Android #0-0]
[tests/performance/apdex-score/apk/CHTAndroid.apk Android #0-0] » /tests/performance/apdex-score/test/specs/num-1/test.apdex.js
[tests/performance/apdex-score/apk/CHTAndroid.apk Android #0-0] Apdex Performance Workflows
[tests/performance/apdex-score/apk/CHTAndroid.apk Android #0-0]    ✓ should load contact list
[tests/performance/apdex-score/apk/CHTAndroid.apk Android #0-0]    ✓ should load CHW area
[tests/performance/apdex-score/apk/CHTAndroid.apk Android #0-0]    ✓ should load Household
[tests/performance/apdex-score/apk/CHTAndroid.apk Android #0-0]    ✓ should create patient
[tests/performance/apdex-score/apk/CHTAndroid.apk Android #0-0]    ✓ should load patient
[tests/performance/apdex-score/apk/CHTAndroid.apk Android #0-0]    ✓ should submit patient report
[tests/performance/apdex-score/apk/CHTAndroid.apk Android #0-0]    ✓ should search patient
[tests/performance/apdex-score/apk/CHTAndroid.apk Android #0-0]    ✓ should load message list and view a message
[tests/performance/apdex-score/apk/CHTAndroid.apk Android #0-0]    ✓ should load task list and view a task
[tests/performance/apdex-score/apk/CHTAndroid.apk Android #0-0]    ✓ should load report list and view a report
[tests/performance/apdex-score/apk/CHTAndroid.apk Android #0-0]    ✓ should load analytics and relaunch the app
[tests/performance/apdex-score/apk/CHTAndroid.apk Android #0-0]
[tests/performance/apdex-score/apk/CHTAndroid.apk Android #0-0] 11 passing (23m 3s)


Spec Files:	 1 passed, 4 skipped, 5 total (100% completed) in 00:23:20  
```

> these can change with dates and also when we run tests that create new patients for the same household multiple times - like the should create patient test

We should be able to control the dates, and it would be a good idea to clean up after the tests are run. What do you think?

> Also, regarding the important thing you mentioned about running the tests with a cht local set-up - the same thing applies for this as well - each one of these tests can be executed successfully on any config - you'd just need to adjust the settings.json file to match the elements displayed and configured for that local instance

Are you planning to adjust the settings.json file to run with a cht local set-up as part of this PR?

**Comment by ralfudx** [comment]
Thanks for testing this @lorerod . I'm glad you were able to run the tests successfully.
I'm not planning to adjust the 'settings.json' file to run on a local cht instance as part of this PR but if you really want to do this, we can set-up a call anytime soon or maybe during the Monday QA Sync and I can show you.

**Comment by ralfudx** [comment]
@Benmuiruri @lorerod when you have some time, can you kindly provide final review feedback on this so that we can merge and close the ticket?

**Comment by Benmuiruri** [comment]
I have been trying all morning but I've not been successful so far. The test is seeing the element although it is on the viewport. I have switched to resolving requested [changes](https://github.com/medic/cht-core/pull/9128) to the more urgent supervisor feature.  I will be back to trouble shoot this in the evening. 
Screenshot 2024-06-06 at 11 59 44

**Review by Benmuiruri — APPROVED** [review]
I was able to run the tests successfully. On the first run I had one failure (the phone sometimes glitches, maybe its the cable connection or something) but I was able to run them all in the end, even running some of the tests 

Screenshot 2024-06-10 at 15 49 38

**Pull request merged**
