### PR TITLE
Expose moment library in nools partner code

### PR DESCRIPTION
**Pull request by kennsippell**
# Description

#6296 

# Code review items

- Readable: Concise, well named, follows the [style guide](https://github.com/medic/medic-docs/blob/master/development/style-guide.md), documented if necessary.
- Documented: Configuration and user documentation on [medic-docs](https://github.com/medic/medic-docs/)
- Tested: Unit and/or e2e where appropriate
- Internationalised: All user facing text
- Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in Changes.md.

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

### CODE REVIEW

**Comment by kennsippell** [comment]
@garethbowen Thoughts on including this in 3.9.0?

**Comment by garethbowen** [comment]
While this change may appear simple it is in fact very complex as it expands our supported API by an order of magnitude or two. As discussed previously this would make it very difficult to switch to another implementation in the future as this could cause breaking changes in configuration. Moreover, simply bumping the version of moment.js we use could cause a breaking change that would be very hard to detect, potentially locking us to an old implementation of moment.

Instead I would support extending nootils to include specific date functions that are most useful, which are implemented in moment js behind the scenes. That way we can change the implementation without breaking our API, and have tests to ensure backwards compatibility is maintained.

Is it possible to come up with a subset of functionality that is frequently used in configurations?

**Comment by kennsippell** [comment]
@garethbowen  I see your concerns. Some thoughts

* moment.js did [one release](https://github.com/moment/moment/releases) last year! This thing is stable.
* moment.js uses semver. We use semver. So are you only talking about upgrading to a new breaking version of moment? How likely is that to be essential before we can remove nools?
* This moment object is initialized with the correct locales and defaults to correct locale for the user.
* Adding new custom datetime interfaces to Utils increases our educational burdens to technical partners. 
* Based on the change history of momentjs, I doubt our tests abilities to catch the very subtle changes that are likely to be made.
* What do you think of [this](https://github.com/medic/cht-core/issues/5906#issuecomment-561286749) proposed plan to get rid of nools in core and add it as an optional dependency in medic-conf?  This hopefully slightly mitigates some of your long-term concerns.
* It's hard to reduce moment to a ordered list of high-value "useful" interfaces. It's a great library and a lot a lot of our partner code is date manipulation. We cause a lot of bugs because we need to write and rewrite this stuff custom each time.

What about exposing this via Utils.moment()? It is perhaps a decent compromise with more abilities for contingencies.

**Comment by kennsippell** [comment]
@garethbowen Can you share thoughts on how to move this forward?

**Comment by garethbowen** [comment]
We can have a look at how to solve this once the issue is prioritised. I've moved it to the App Builders backlog so you can lobby for it.

**Comment by kennsippell** [comment]
There is a working solution here in this PR. If you can please provide guidance on how to fix the issue I'd like to pursue a contribution in my spare time.

**Comment by garethbowen** [comment]
moment.js is stable and hasn't changed significantly recently which makes this tempting.

The fact that they follow semver doesn't help here as core upgrading would still add upgrade burden because there's no way for core to know if the configuration will break or not. Furthermore it would force us to make a major release to properly communicate the broken backwards compatibility. This would be even worse if core decided to migrate from moment to another library, as we just did for underscore to lodash. It's important that core is free to make this sorts of changes and test that it's backwards compatible so our partners have the confidence to upgrade frequently.

Exposing moment on `utils.moment` has the same issues.

One more thing to consider is are there other libraries that would be useful? I suspect moment.js is the _most_ useful but I imagine there are other libraries that may be useful from time to time.

> What do you think of this proposed plan to get rid of nools in core and add it as an optional dependency in medic-conf? This hopefully mitigates your long-term concerns.

I think this solves all my concerns. If there's a way to include any library you like in the compiled code then the library and version chosen can be completely independent of any library and version that the core deployment has. The main downside to this approach is the moment library would be included in _both_ the bundled app and the bundled config. I think this can be mitigated sufficiently by making sure tree shaking is working in the built config so unused library functions are discarded.

**Comment by garethbowen** [comment]
Closing as discussed (but I'll leave the branch around). DM me if you think this should be merged as is.

**Pull request closed without merging**
