### PR TITLE
Upgrade dependencies in 3.12

### PR DESCRIPTION
**Pull request by latin-panda**
# Description

In this PR:
- Upgrade of some dependencies across internal projects.
- Removed old leftover comment from when we did the Angular migration. 

Please refer to [this document](https://docs.google.com/spreadsheets/d/1hUSJxTV75Iq-YNOmJ_va7ulAoZV9Ntj5rFtrFzppwLA/edit?usp=sharing) for the list of dependencies that got updated and the ones that couldn't be upgraded + short notes.

https://github.com/medic/cht-core/issues/6969

# Code review checklist

- [ ] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- [ ] Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- [ ] Tested: Unit and/or e2e where appropriate
- [ ] Internationalised: All user facing text
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

### CODE REVIEW

**Comment by latin-panda** [comment]
Hi @garethbowen! Can you please review this PR? Is this okay to how it's normally done? 
Thanks!

**Comment by garethbowen** [comment]
I'm sorry I don't have availability to review this in a timely manner. @njogz Would you mind taking over?

**Comment by njogz** [comment]
I don't mind. Glad to review.

**Review by njogz — APPROVED** [review]
Good job on this. The document you created was very thorough and made my work much easier. We should create tickets for upgrading the packages that have breaking changes and need to be verified e.g. mocha

**Pull request merged**
