### PR TITLE
chore(#9153): acknowledge contributors in release notes

### PR DESCRIPTION
**Pull request by garethbowen**
# Description

#9153

# Code review checklist

- [ ] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- [ ] Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- [ ] Tested: Unit and/or e2e where appropriate
- [ ] Internationalised: All user facing text
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# Compose URLs
If Build CI hasn't passed, these may 404:

* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9153-thank-contributors/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9153-thank-contributors/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9153-thank-contributors/docker-compose/cht-couchdb-clustered.yml)

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

### CODE REVIEW

**Comment by garethbowen** [comment]
Outputs something like...

```
## Contributors

Thanks to all who committed changes for this release!

- [Jennifer Q](https://github.com/latin-panda)
- [Diana Barsan](https://github.com/dianabarsan)
- [Gareth Bowen](https://github.com/garethbowen)
- [Daniel](https://github.com/nydr)
- [Joshua Kuestersteffen](https://github.com/jkuester)
- [Ashley](https://github.com/mrjones-plip)
- [Fred](https://github.com/freddieptf)
- [Ben Kiarie](https://github.com/Benmuiruri)
- [Lore](https://github.com/lorerod)
```

**Review by mrjones-plip — CHANGES_REQUESTED** [review]
nice work! This a small gesture that will go a long way to welcoming outside devs and encouraging internal devs  

I ran some tests using this signature `node ./scripts/release-notes cht-core VERSION  --skip-commit-validation` :

*  `4.9.0` with it seems OK:

     ```
     - [Jennifer Q](https://github.com/latin-panda)
     - [Ben Kiarie](https://github.com/Benmuiruri)
     - [Diana Barsan](https://github.com/dianabarsan)
     - [Michael Kohn](https://github.com/michaelkohn)
     - [Ashley](https://github.com/mrjones-plip)
     - [Daniel](https://github.com/nydr)
     ```

*  `3.15.0` is empty (no one listed) which seems wrong based off the milestone having [20 issues](https://github.com/medic/cht-core/milestone/98?closed=1)
*  `3.16.0` has some `null` values we should defend against:

     ```
     - [Mokhtar](https://github.com/m5r)
     - [Gareth Bowen](https://github.com/garethbowen)
     - [null](https://github.com/elvisdorkenoo)
     - [Njuguna Ndung'u](https://github.com/njogz)
     - [Diana Barsan](https://github.com/dianabarsan)
     ```

**Comment by garethbowen** [comment]
I've added code to handle the nulls - thanks for finding that!

Currently the script doesn't support validating commits (previous to this change) or the list of commit authors (this change) for anything except the latest release. This is because of the `getLatestReleaseName` function which does just as it says. The code then gets commits from the `latestRelease` until the tag you provide.

If I modify the code to hardcode this value, eg: `const latestReleaseName = '3.14.0'; //await getLatestReleaseName();` and then run with `node ./scripts/release-notes cht-core 3.15.0` then I get this:

```
- [Diana Barsan](https://github.com/dianabarsan)
- [Ashley](https://github.com/mrjones-plip)
- [Jennifer Q](https://github.com/latin-panda)
- [Gareth Bowen](https://github.com/garethbowen)
- [bedengaruko](https://github.com/bedengaruko)
- [Joshua Kuestersteffen](https://github.com/jkuester)
- [Nick Christenson](https://github.com/newtewt)
- [Njuguna Ndung'u](https://github.com/njogz)
- [Mokhtar](https://github.com/m5r)
- [Binod Adhikary](https://github.com/binokaryg)
- [Aidan](https://github.com/aodhan-domhnaill)
```

I think this is ok, or at least, a known bug. The correct solution would be to somehow get release name before this one which is probably possible with github but might be complicated...

**Review by mrjones-plip — APPROVED** [review]
awesome - thanks for the updates!

**Comment by garethbowen** [comment]
Merged bypassing the failing build as it's unrelated.

**Pull request merged**
