### PR TITLE
chore: Replace mockserver with nginx

### PR DESCRIPTION
**Pull request by nydr**
# Description

Replaces the mockserver used in some tests with a slim nginx image.

This is primarily to reduce the image size required for mocking these tests from 120mb to 5mb but will also slightly reduce resource requirements for these tests.

# Code review checklist

- [ ] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- [ ] Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- [ ] Tested: Unit and/or e2e where appropriate
- [ ] Internationalised: All user facing text
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# Compose URLs
If Build CI hasn't passed, these may 404:

* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:replace-mockserver/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:replace-mockserver/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:replace-mockserver/docker-compose/cht-couchdb-clustered.yml)

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

### CODE REVIEW

**Review by mrjones-plip — CHANGES_REQUESTED** [review]
@nydr - nice work to reduce image size and get some more performance out of our tests!

I'm not quite sure how to review this, can you give me some more guidance?

* I tried running `make test` on both `master` and `replace-mockserver` and they look the same.  Good I guess?  There are some errors (eg `2 failed, 11 passed in 1.46s`) - but maybe since they're the same that's OK?
* `docker compose up` works, but `GET` request to `/`, `/_membership` and `/error/drop` don't work as I'd expect (`up` is returned in a browser, and nothing in `curl`).  However, this behaivor is the same in `master` and `replace-mockserver` - so maybe OK?

**Comment by nydr** [comment]
@mrjones-plip Thanks for checking on this! There's three instances where it's being used:
```shell
### 1) Nginx
# Should work exactly as before, to test:
❯ cd nginx/tests/ && make test

### 2) Haproxy
# Here I also increased the number of mock servers from 1 to 3 so it'll take
# clustered couchdb into account, to test:
❯ cd haproxy/tests/ && make test

### 3) Haproxy-healthcheck
# Should work exactly as before, not used in any automated tests but used for
# testing haproxy-healthcheck during development
❯ cd haproxy-healthcheck
❯ docker-compose up

❯ curl localhost:5984/_membership
{ "all_nodes": [ "mock-couchdb" ], "cluster_nodes": [ "mock-couchdb" ] }

❯ nc localhost 5555
up
```

> * I tried running `make test` on both `master` and `replace-mockserver` and they look the same.  Good I guess?  There are some errors (eg `2 failed, 11 passed in 1.46s`) - but maybe since they're the same that's OK?

Which tests are failing? There was some issues I didn't see on my machine or CI last time https://github.com/medic/cht-core/pull/8446#discussion_r1290741374 and while not directly related to this PR I think it's worth investigating further

> * `docker compose up` works, but `GET` request to `/`, `/_membership` and `/error/drop` don't work as I'd expect (`up` is returned in a browser, and nothing in `curl`).  However, this behaivor is the same in `master` and `replace-mockserver` - so maybe OK?

I'm not sure I follow, could you walk me through how you're using curl? `haproxy-healthcheck` is the only compose file which exposes the mock server port and there I'm seeing this:
```shell
❯ curl -w "\n" localhost:5984/{,_membership,error/drop}
{ "couchdb": "Welcome to mock-couchdb", "status": "this field is not used" }
{ "all_nodes": [ "mock-couchdb" ], "cluster_nodes": [ "mock-couchdb" ] }
curl: (52) Empty reply from server

```

`up` might be coming from the healthcheck itself, (port `5555`) and that is a plain tcp server (not http)
```shell
❯ nc -v localhost 5555
Connection to localhost port 5555 [tcp/personal-agent] succeeded!
up
```

**Review by mrjones-plip — APPROVED** [review]
@nydr  - thanks for the detailed notes!  This is helpful.  The main thing I was missing was (embarrassingly) specifying the port `5984`. With your updated steps and on your `replace-mockserver` branch, the `make test` look good  for `nginx/test/` and `haproxy/test` and now the `docker compose up` call followed by `curl` does work.  `nc` also works as expected  (you guessed right!)

on the `master` branch the `curl` call fails but `nc` succeeds:

```
➜  haproxy-healthcheck git:(master) curl localhost:5984/_membership

curl: (7) Failed to connect to localhost port 5984: Connection refused
➜  haproxy-healthcheck git:(master) nc localhost 5555
up
```

That OK? I'll assume use and approve to unblock!

**Comment by nydr** [comment]
Thank you for the quick response!

> on the `master` branch the `curl` call fails but `nc` succeeds
> That OK? I'll assume use and approve to unblock!

Yeah that's fine, on master there was no port forwarding configured for that service in the compose file so it's expected behaviour. Additionally that service is only intended to be used for ad-hoc tests during development of haproxy-healthcheck which will hopefully be sunset at some point in the future.

**Pull request merged**
