### PR TITLE
doc(#8997): adds explanatory comment for .browserslistrc settings

### PR DESCRIPTION
**Pull request by fardarter**
I have added a rationale comment for the .browserslistrc file. 

Addresses issue https://github.com/medic/cht-core/issues/8997

### CODE REVIEW

**Comment by fardarter** [comment]
@garethbowen I see you closed the issue but thought this was still valuable.

**Review by garethbowen — APPROVED** [review]

**Comment by garethbowen** [comment]
Good call, thanks. I think I'll also add that rationale to the docs site when I'm back in the office.

**Comment by fardarter** [comment]
> Good call, thanks. I think I'll also add that rationale to the docs site when I'm back in the office.

@garethbowen can't imagine why this would cause a test failure. Would you be able to rerun the failing test?

**Comment by garethbowen** [comment]
Looks like this known issue: https://github.com/medic/cht-core/issues/8936

**Pull request merged**
