### PR TITLE
Fix incorrect reference to controller state

### PR DESCRIPTION
**Pull request by garethbowen**
# Description

#6835 

# Code review items

- Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- Tested: Unit and/or e2e where appropriate
- Internationalised: All user facing text
- Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

### CODE REVIEW

**Comment by garethbowen** [comment]
@njogz Review please! No hurry on this but it fixes up a couple of regressions. It'll obviously conflict with the angular upgrade so I won't merge this till that's merged and I've sorted out the conflicts.

**Comment by njogz** [comment]
@garethbowen looks good. Wondering whether we should merge this to the angular migration plan branch instead and have it tested with all the other changes. What do you think?

**Comment by garethbowen** [comment]
@njogz Thanks! I'd prefer not to complicate that already complex PR, so once that's merged I'll forward port this solution and submit it for testing separately.

**Comment by garethbowen** [comment]
This is replaced by https://github.com/medic/cht-core/pull/6976

**Pull request closed without merging**
