### PR TITLE
chore: improve style of menu buttons and labels

### PR DESCRIPTION
**Pull request by GallyTi**
# Description

Improve Sidebar Menu's button and label placement

#9481

# Code review checklist

- [ x] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- [ ] Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- [ ] Tested: Unit and/or e2e where appropriate
- [ x] Internationalised: All user facing text
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

### CODE REVIEW

**Comment by latin-panda** [comment]
Thanks for sending this @GallyTi, I'll be reviewing your PR tomorrow. 

[The Pull Request](https://docs.communityhealthtoolkit.org/contribute/code/workflow/#opening-pull-requests) title will be the commit message before merging. I have updated the title to follow the [commit message format](https://docs.communityhealthtoolkit.org/contribute/code/workflow/#commit-message-format).

**Review by latin-panda — CHANGES_REQUESTED** [review]
Nice start!

It can get tricky with CSS since everything needs to align. 
My advice is to keep changes at minimum, work with the icons first and leave changes to labels as last option. 
Let me know if you need with anything

**Comment by GallyTi** [comment]
Hello @latin-panda,

I apologize for the inconvenience. I needed a fresh start, so I created a new git clone and a new branch, which led to this new pull request. I’m really sorry for the trouble, but everything should now be properly aligned as requested, with cleaner and more organized code.

Thank you for your understanding!

If it is possible i will link this pull request to the new one, and pelase close or remove this pull request. Thank you! 🥺🥺

https://github.com/medic/cht-core/pull/9545

**Comment by latin-panda** [comment]
That's okay @GallyTi, thank you for your time on this. I'll review the other PR tomorrow :)

**Pull request closed without merging**
