### PR TITLE
chore(#8181): refactor send message test for reports

### PR DESCRIPTION
**Pull request by kapelo**
# Description

Refactor send message for reports test due to @tatilepizs 's [recommendation](https://github.com/medic/cht-core/pull/9353)

https://github.com/medic/cht-core/issues/8181
https://github.com/medic/care-teams/issues/148

# Code review checklist

- [ ] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- [ ] Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- [ ] Tested: Unit and/or e2e where appropriate
- [ ] Internationalised: All user facing text
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# Compose URLs
If Build CI hasn't passed, these may 404:

* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:e2e-send-message-refactor/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:e2e-send-message-refactor/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:e2e-send-message-refactor/docker-compose/cht-couchdb-clustered.yml)

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

### CODE REVIEW

**Review by tatilepizs — APPROVED** [review]
Thank you for applying the suggestions @kapelo, it looks great. 🌟

**Review by ralfudx — APPROVED** [review]
Looks good

**Review by latin-panda — APPROVED** [review]
Nice clean up, thank you! 
Ready to merge, remember to close the ticket https://github.com/medic/care-teams/issues/148 
🤩

**Review by Benmuiruri — APPROVED** [review]
LGTM

**Pull request merged**
