### PR TITLE
Enables bundlesize and runs publish before test

### PR DESCRIPTION
**Pull request by dianabarsan**
# Description

Also, don't log debug messages in production. 

# Code review items

- Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- Tested: Unit and/or e2e where appropriate
- Internationalised: All user facing text
- Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

### CODE REVIEW

**Comment by dianabarsan** [comment]
hey @garethbowen 

I got the 1st maybe close to reality bundlesize results. 
We need to set new limits, I tried configuring bundlesize to check "all" js files (with a wildcard) but it still did a 1by1 check. 
We don't have d3 bundled yet, so I'm not sure what impact that will have, so my scripts.js limit might be optimistic :D 
So far, the bundle is a few KB smaller than master: 836KB vs 796KB. 

Would you mind having a look? 

Thank you!

**Comment by dianabarsan** [comment]
Oh, and I made Travis skip e2e tests so I get something published so I can check a horti upgrade. Also because it takes hours to get jobs in queue :(

**Review by garethbowen — APPROVED** [review]
Nice one.

Another way to speed the build up would be to run the `publish` as part of the `compile` stage - I think we end up going to the back of the queue every time a stage completes so fewer stages means less time in the queue.

I'm not too worried about the bundlesize - let's see where it lands when everything is migrated.

**Comment by dianabarsan** [comment]
Yea, I thought about that too. For some reason, I wanted to do as little temporary changes to the file as possible. I'll make the change.

**Comment by dianabarsan** [comment]
Thanks!

**Comment by dianabarsan** [comment]
I remembered why I didn't want to do any changes to the build :) Because I didn't want to wait for 4 hours just to see I made a mistake and the change doesn't work :D

**Pull request merged**
