### PR TITLE
Remove existent backend servers before adding more.

### PR DESCRIPTION
**Pull request by dianabarsan**
# Description

Removes existent backend servers from haproxy config before adding the current ones. 

# Code review checklist

- [ ] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- [ ] Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- [ ] Tested: Unit and/or e2e where appropriate
- [ ] Internationalised: All user facing text
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

### CODE REVIEW

**Review by garethbowen — APPROVED** [review]
Makes sense.

A slightly cleaner solution would be to use multiple haproxy config files - one that's static and one that's entirely generated. That way we could just drop the previous one and create a brand new one rather than having to sed and append.

Still, approved! We can improve things as we go...

**Comment by dianabarsan** [comment]
> A slightly cleaner solution would be to use multiple haproxy config files

I really like this idea. And I don't think it's hard to implement!

**Comment by dianabarsan** [comment]
I've split the config in two files. I am of two minds about splitting them further. Let me know what you think, @garethbowen . Thank you!

**Review by garethbowen — APPROVED** [review]
Awesome!

**Pull request merged**
