### PR TITLE
fix(#8844): adding link to exit error page

### PR DESCRIPTION
**Pull request by latin-panda**
# Description

Adds a link to the exit error page and test coverage of new code. 
- When no navigation history (hard-reload) navigates to Home (message tab in default config)
- When 
  - "access denied" and "no found" navigate to the previous page, shows `back` label to match error message context ([conversation with Nicole](https://medic.slack.com/archives/C02GME3BQE6/p1710791439222369?thread_ts=1710759172.451819&cid=C02GME3BQE6)).
  - Any other error navigates to the previous page and shows `Reload application` label

Tests: 

https://github.com/medic/cht-core/assets/66472237/990b3dbc-84a3-46e9-926e-4f095748f729

<details>
<summary>Desktop view</summary>

Screenshot 2024-03-25 at 7 01 04 PM
</details>

<details>
<summary>Mobile view</summary>

Screenshot 2024-03-25 at 7 00 57 PM
</details>

#8844 

# Code review checklist

- [ ] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- [ ] Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- [ ] Tested: Unit and/or e2e where appropriate
- [ ] Internationalised: All user facing text
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# Compose URLs
If Build CI hasn't passed, these may 404:

* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8844-exit-link-in-error-page/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8844-exit-link-in-error-page/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8844-exit-link-in-error-page/docker-compose/cht-couchdb-clustered.yml)

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

### CODE REVIEW

**Comment by latin-panda** [comment]
@Benmuiruri this is not finished yet, but I wanted to share the solution so far and get your opinion

**Comment by latin-panda** [comment]
@Benmuiruri are you okay with this solution? 
I'll get the test done but I'd like to know if you are okay with this

**Review by Benmuiruri — COMMENTED** [review]
Looks okay as we discussed.

**Comment by latin-panda** [comment]
@Benmuiruri @ralfudx this is ready for review

**Comment by ralfudx** [comment]
@latin-panda from the screenshots there seems to be a mix-up between the pages - according to the [conversation](https://medic.slack.com/archives/C02GME3BQE6/p1710791439222369?thread_ts=1710759172.451819&cid=C02GME3BQE6), the `back` link should be displayed on the no-access page while the `reload` link should be displayed on the error page

**Comment by latin-panda** [comment]
@ralfudx I didn't read Nicole's feedback correctly. Thanks for catching it!
I have fixed it and also changed the `Not Found` page to have `Back` since it makes more sense when the URL doesn't match any page. All the screenshots and video have been updated. 

- "access denied" and "no found" navigate to the previous page, shows back label to match error message context.
- Any other error navigates to the previous page and shows Reload application label

Please have a look

**Review by Benmuiruri — COMMENTED** [review]
Looks good but I noticed something just want to confirm it is the intended behaviour. 

I have attached a video demonstrating the following.
1. If you enter a wrong url you are directed to the `Error Page` and you can click the `Back` button to return to the previous working URL.
2. If you enter a wrong url, you are directed to the `Error Page`. If you enter a wrong url again, no matter how many times you click the `Back` button. It does not take you back to the previous working URL

https://github.com/medic/cht-core/assets/2597305/8484158c-3246-48c9-8894-c8a3a857ab50

Is that the intended behaviour ?

**Comment by latin-panda** [comment]
Thanks @Benmuiruri. This is because the previous URL is not valid (404) and then redirects back to the error page. Angular doesn't have a reliable way to check if a given URL is valid before resolving it. The fix I made is to navigate back to the home page if the previous URL is the Error page. That means the second time a user is on the Error page. 

I have cover this in the unit tests and also here is the video showing the test after fixing the bug: 
https://github.com/medic/cht-core/assets/66472237/906410cf-28b5-4539-9401-767e96e37514

**Review by ralfudx — APPROVED** [review]
LGTM

**Review by Benmuiruri — APPROVED** [review]
Awesome.

**Pull request merged**
