### PR TITLE
fix(#8580) fix docker exec calls to be git bash compatible

### PR DESCRIPTION
**Pull request by mrjones-plip**
# fix docker exec calls to be git bash compatible

This PR removes the `-it` flag to the `docker exec` calls in the docker helper script per this ticket:

> When running [some linux command], most of the time you don't need the `-it` (aka **STDIIN** via `--interactive and **STDOUT** via `--tty` for the psuedo-tty options)

This should be backwards compatible with linux/mac/wsl2 and be forwards compatible with git BASH where the error was discovered.

per medic/cht-core#8580

# Code review checklist

- [X] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- [ ] Tested: Unit and/or e2e where appropriate
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# Compose URLs

If Build CI hasn't passed, these may 404:

* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8580-gitbash-docker-helper/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8580-gitbash-docker-helper/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8580-gitbash-docker-helper/docker-compose/cht-couchdb-clustered.yml)

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

### CODE REVIEW

**Comment by mrjones-plip** [comment]
to test:
* checkout this branch
* start a new  docker helper project 
* make sure there's no errors
* make sure TLS works and there's not a self signed cert

NB - you'll see two errors `ip: command not found` and `"listen ... http2" directive is deprecated`.  Both can be ignored and the latter is covered in #8582

**Comment by mrjones-plip** [comment]
oh - awesome - thanks @tatilepizs ! I'll see if something changed in 4.4 and get back to you!

**Comment by mrjones-plip** [comment]
hmmm - your output matches what I saw in #8582 which I filed when working on this issue.  It comes up in CHT 4.4 where we allow `http2` as well as `http1.x`.

I think this issue is unrelated though...but we should figure it out!  I'll try and find some time we can connect this week on this!

**Comment by mrjones-plip** [comment]
Ah ha!  I've reproduced the issue you found - nice work finding it.  I still think it's separate from this ticket, but let me do a bit more debugging.  I don't need to chat real time now that i've reproduced it:

```
2023/09/27 22:02:16 [emerg] 30#30: open() "/etc/nginx/conf.d/server.conf" failed (2: No such file or directory) in /etc/nginx/nginx.conf:70
nginx: [emerg] open() "/etc/nginx/conf.d/server.conf" failed (2: No such file or directory) in /etc/nginx/nginx.conf:70
```

Odd though, line 70 of `nginx.conf` is ` include /etc/nginx/conf.d/server.conf;` and that file is there:

```
➜  docker-helper-4.x git:(master) docker exec -it 4_4_cert_test_nginx_1  ls /etc/nginx/conf.d/server.conf
/etc/nginx/conf.d/server.conf

➜  docker-helper-4.x git:(master) docker exec -it 4_4_cert_test_nginx_1 cat  /etc/nginx/conf.d/server.conf
resolver 127.0.0.11 valid=10s; # 127.0.0.11 is from default /etc/resolv.conf
set $upstream_endpoint http://api:5988;

location / {
  proxy_pass              $upstream_endpoint;
  proxy_set_header        Host            $host;
  proxy_set_header        X-Real-IP       $remote_addr;
  proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header        X-Forwarded-Proto https;
  proxy_set_header        X-Forwarded-Host $server_name;
}
```

I'll try on 4.3 - and keep I'll keep digging!

**Comment by mrjones-plip** [comment]
hrm - now running `../add-local-ip-certs-to-docker-4.x.sh 4_4_cert_test_nginx_1` did fix the issue - so I wonder if it's just a semi-common failure to load in the script?  We could retry maybe? 

I'll dig some more!

**Comment by mrjones-plip** [comment]
@tatilepizs  - sorry for the delay in getting back to you!

I had a theory that I'd like you test: only when there's no volumes, image or containers does the cert fail to download.  

I have an test instance I called `4_4_test`:

```
pwd
/home/mrjones/Documents/MedicMobile/cht-core/scripts/docker-helper-4.x

cat 4_4_test.env 
NGINX_HTTP_PORT=10101
NGINX_HTTPS_PORT=10463
COUCHDB_USER=medic
COUCHDB_PASSWORD=password
CHT_COMPOSE_PROJECT_NAME=4_4_test
DOCKER_CONFIG_PATH=/home/mrjones/.medic/cht-docker/4_4_test-dir
COUCHDB_SECRET=5cb70d9a877c3c4d4f3a23784de9fc72
COUCHDB_UUID=44324693cb17031f136f75b9c17f6fdd
COUCHDB_DATA=/home/mrjones/.medic/cht-docker/4_4_test-dir/couch
CHT_COMPOSE_PATH=/home/mrjones/.medic/cht-docker/4_4_test-dir/compose
CHT_NETWORK=4_4_test-cht-net
```

Now if I delete everything with this super delete command I crafted:

```
docker kill $(docker ps -q); docker rm 4_4_test_api_1 4_4_test_couchdb_1 4_4_test-dir-cht-upgrade-service-1 4_4_test_haproxy_1 4_4_test 4_4_test_haproxy_1 4_4_test_healthcheck_1 4_4_test_nginx_1 4_4_test_sentinel_1;docker image rm -f public.ecr.aws/medic/cht-nginx:4.4.0 public.ecr.aws/medic/cht-haproxy-healthcheck:4.4.0 public.ecr.aws/medic/cht-haproxy:4.4.0 public.ecr.aws/medic/cht-couchdb:4.4.0 public.ecr.aws/medic/cht-sentinel:4.4.0 public.ecr.aws/medic/cht-api:4.4.0;docker volume rm -f 4_4_test_cht-ssl;docker volume rm -f 4_4_test_cht-credentials;
```

I can reliably get the TLS not installed error, and reliably fix it by `kill`ing and restarting the container.  Here's a video of showing it happen just after I issued the delete command for the 4th time:

https://github.com/medic/cht-core/assets/8253488/505ca80f-33a1-4e97-b11b-da5af9061d29

I noticed you were on `master` on your tests, and you were testing against version `4.4.0` in  [your screenshot](https://user-images.githubusercontent.com/94494491/270788311-9f71c5af-265f-40c4-b484-966d0bae6421.png), just like I was.

If you agree this is an unrelated issue, we can test the PR as is and file a separate issue about the certs not being installed on first run with no images and volumes (something I'm pretty sure I've seen in the past!)

**Comment by tatilepizs** [comment]
Thank you @mrjones-plip for investigating this issue. 

I followed your instructions and had the same result

[video](https://github.com/medic/cht-core/assets/94494491/965c4372-2b5d-4768-8676-f0ca4ab35b96)

> If you agree this is an unrelated issue, we can test the PR as is and file a separate issue about the certs not being installed on first run with no images and volumes (something I'm pretty sure I've seen in the past!)

I agree 😄 thank you!

**Review by tatilepizs — APPROVED** [review]
Working perfectly, thank you @mrjones-plip ✨

**Comment by mrjones-plip** [comment]
awesome - thanks for the thorough confirmation of my firs time run theory and the QA on this!

tracking TLS issue here:
* https://github.com/medic/cht-core/issues/8612

**Pull request merged**
