### PR TITLE
chore(#8128): Update release templates

### LINKED ISSUE #8128: Add clarifications to the release templates
**What feature do you want to improve?**
While going through the release process for [4.1.1](https://github.com/medic/cht-core/issues/8116), I noticed a few guidelines that don't seem up-to-date. For example, `Write an update in the weekly Product Team call agenda ` is not accurate anymore, as we don't hold weekly Product Team calls.

**Describe the improvement you'd like**
Suggest updates to the existing [release templates](https://github.com/medic/cht-core/tree/master/.github/ISSUE_TEMPLATE).

### PR DESCRIPTION
**Pull request by andrablaj**
# Description

Adds updates and clarifications to the existing [release templates](https://github.com/medic/cht-core/tree/master/.github/ISSUE_TEMPLATE).

Closes #8128 

# Code review checklist

- [ ] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- [ ] Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- [ ] Tested: Unit and/or e2e where appropriate
- [ ] Internationalised: All user facing text
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# Compose URLs

If Build CI hasn't passed, these may 404:

* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8128-update-release-templates/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8128-update-release-templates/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8128-update-release-templates/docker-compose/cht-couchdb-clustered.yml)
 
# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

### CODE REVIEW

**Comment by andrablaj** [comment]
@garethbowen, some other areas that need attention:

- The [market link](https://staging.dev.medicmobile.org/builds_4/releases) is broken. Please fix the redirect to [this link](https://staging.dev.medicmobile.org/_couch/builds_4/_design/builds/_view/releases).
- CI failed when bumping the version. Do you think we should add a clarification advising the release engineer to retry or contact the development team to see if merging is safe?
- If the Director of Technology is out of the office, who should be the reviewer for the `cht-docs `update?

Thanks!

**Review by garethbowen — APPROVED** [review]
Thanks!

**Comment by garethbowen** [comment]
> CI failed when bumping the version. Do you think we should add a clarification advising the release engineer to retry or contact the development team to see if merging is safe?

I think it's ok. We're working on stabilizing the CI which will solve this.

> If the Director of Technology is out of the office, who should be the reviewer for the cht-docs update?

Let's just drop that requirement and pick anyone for cht-docs. I watch the repo anyway and can submit an update PR if I notice anything is off.

**Comment by garethbowen** [comment]
@andrablaj 

> The [market link](https://staging.dev.medicmobile.org/builds_4/releases) is broken. Please fix the redirect to [this link](https://staging.dev.medicmobile.org/_couch/builds_4/_design/builds/_view/releases).

What redirect? Can you update the link in the template?

**Comment by garethbowen** [comment]
> What redirect?

For anyone else finding this the solution is to add an entry into the vhosts section of the couchdb configuration.

**Comment by andrablaj** [comment]
I forgot to squash before merging, sorry for that. 😞

**Pull request merged**
