### PR TITLE
Removed report rating analytics

### PR DESCRIPTION
**Pull request by latin-panda**
# Description

Removed analytics reporting rates and unneeded dependencies.

https://github.com/medic/angular10-migration/issues/26
and https://github.com/medic/cht-core/issues/6248

# Code review items

- Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- Tested: Unit and/or e2e where appropriate
- Internationalised: All user facing text
- Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

### CODE REVIEW

**Comment by garethbowen** [comment]
I know this is still in draft but I could resist having a look. I think you can also delete these views: `reports_by_form_year_month_places` and `reports_by_form_year_week_places`

**Comment by latin-panda** [comment]
Hi @dianabarsan, when you have chance, can you please review this one? Thank you!

**Review by dianabarsan — APPROVED** [review]
So happy to see this go! 

Just one small comment: I think we should remove comments about d3 from `main.ts`: https://github.com/medic/cht-core/blob/4750-angular-10-take-2/webapp/src/ts/main.ts#L12

**Comment by latin-panda** [comment]
I removed the comment and the polyfill reference, thank you!

**Comment by dianabarsan** [comment]
Please also remove:
```
//require('nvd3');
```

nvd3 was the angular d3 bridge library.

**Comment by latin-panda** [comment]
nvd3 removed!

**Pull request merged**
