### PR TITLE
update helper to pin to cht 4.0.1, use kill instead of stop

### PR DESCRIPTION
**Pull request by mrjones-plip**
# Description

# Code review checklist
- [x] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- [x] Tested: Unit and/or e2e where appropriate

# Compose URLs

If Build CI hasn't passed, these may 404:

* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:helper-to-4.0.1-use-kill-too/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:helper-to-4.0.1-use-kill-too/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:helper-to-4.0.1-use-kill-too/docker-compose/cht-couchdb-clustered.yml)
 
# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

### CODE REVIEW

**Comment by mrjones-plip** [comment]
@dianabarsan - pinging you specifically for this PR mainly b/c of the change from `stop` to `kill`.  I found I often wanted to quickly iterate between local instances and saw that `stop` was slooooow.  In my experience `kill` has been safe enough (and wicked fast :fast_forward: ), but if you think long term it could be detrimental to a developers experience (eg corrupt couch data), lemme know!

**Review by dianabarsan — APPROVED** [review]
i think this is fine. 
just fyi: stop does accept a -t param, which changes how long to wait from stop to kill: https://docs.docker.com/engine/reference/commandline/stop/

**Comment by dianabarsan** [comment]
I'm not sure about the difference between `kill` and `stop -t 0`. I used the latter in my testing.

**Comment by mrjones-plip** [comment]
closing as unmerged in favor of #7956

**Pull request closed without merging**
