### PR TITLE
add node binary and script to upgrade same 

### PR DESCRIPTION
**Pull request by mrjones-plip**
# Description

medic/cht-core#7957

# Code review checklist

- [X] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- [X] Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- [X] Tested: Unit and/or e2e where appropriate

# Compose URLs

If Build CI hasn't passed, these may 404:

* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:7957-node-upgrade-script/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:7957-node-upgrade-script/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:7957-node-upgrade-script/docker-compose/cht-couchdb-clustered.yml)
 
# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

### CODE REVIEW

**Comment by mrjones-plip** [comment]
@garethbowen & @Hareet - before I go much further - [this](https://github.com/medic/cht-core/issues/7957#issuecomment-1350442823) looking OK? You can see source of script [here](https://github.com/medic/cht-core/pull/7983/files) . 

My main concern is that this isn't statically compiled, it's installed via `apt` and then zipped up and stashed in `cht-core` repo.

If we think it looks good, I'll push through more thorough testing steps, including setting up outbound push, and write up a docs page maybe? Open to input!

**Comment by garethbowen** [comment]
@mrjones-plip Sorry but I've run out of time this week (this year...) to review this fully. It _looks_ ok but I'd need to run it to be sure.

**Comment by mrjones-plip** [comment]
"looks OK" is all I'm giong for - thanks  @garethbowen !  It was just if the curl piped through bash was a sane approach.  I'll finish it up and send it over to @Hareet  for a formal review - thanks!

**Comment by mrjones-plip** [comment]
@Hareet  - polished up [test steps here](https://github.com/medic/cht-core/issues/7957#issuecomment-1350442823) - over to you for PR review.

**Comment by Hareet** [comment]
LGTM!

**Pull request merged**
