### PR TITLE
chore(#8982): upgrade to angular 17

### PR DESCRIPTION
**Pull request by garethbowen**
# Description

#8982

# Code review checklist

- [ ] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- [ ] Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- [ ] Tested: Unit and/or e2e where appropriate
- [ ] Internationalised: All user facing text
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# Compose URLs
If Build CI hasn't passed, these may 404:

* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:angular-17/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:angular-17/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:angular-17/docker-compose/cht-couchdb-clustered.yml)

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

### CODE REVIEW

**Comment by garethbowen** [comment]
Needs to be tested on Chrome 90 - blocked on #8963

**Comment by latin-panda** [comment]
@garethbowen Happy to review this, but I'll be unavailable until Wednesday. I suggest asking review of another developer to not block this upgrade

**Comment by garethbowen** [comment]
Ok. Thanks! @Benmuiruri you're up!

**Review by Benmuiruri — APPROVED** [review]
LGTM 

I'm not sure what sort of UI performance testing you had in mind. But I decided to take `Angular Plugin` for a spin. The results kept changing ever so slightly between 16 and 17 here is an example of one of the runs. 

I basically clicked through the Tabs and navigated around in the same path for both 16 and 17.

### Time spent on Angular 17

```
messages 21ms
task component 51.5 ms 
App component 76.8 ms
reports 40 ms 
contacts content 34 ms
contacts content 170 ms 
contacts content 74 ms
contacts content 193 ms 
```

### Time spent on Angular 16

```
messages 13ms 
tasks 40ms
app 66.8 ms
Reports 41.6ms 
contacts content 30ms
contacts content 158 ms 
contacts content 68.8 ms 
contacts content 188.6 ms

**Pull request merged**
