### PR TITLE
Fixes memory leaks

### PR DESCRIPTION
**Pull request by dianabarsan**
# Description

Fixes memory leak caused by saving component references in Redux store.
Fixes memory leak caused by not clearing subscriber references in DB service.
Fixes minor memory leak caused by not clearing references to reports filters. 

https://github.com/medic/angular10-migration/issues/55
https://github.com/medic/angular10-migration/issues/4

# Code review checklist

- [ ] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- [ ] Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- [ ] Tested: Unit and/or e2e where appropriate
- [ ] Internationalised: All user facing text
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

### CODE REVIEW

**Comment by dianabarsan** [comment]
Running this scuffed script, as an offline user, in an **incognito window** (important!, so no extensions), and **with the developer tools closed** (also important, chrome keeps references of clicked things for debug purposes when dev tools are open, so start the script and close the dev tools immediately). 
```
(() => {
  let i = 0;
  const tabTimeToWait = 1500;
  const itemTimeToWait = 800;
  const nbrListItemsPerPage = 30;
  const mInterval = setInterval(() => {
    const listItemIdx = Math.ceil(Math.random() * nbrListItemsPerPage);

    if (i % 5 === 0) {
      $('#messages-tab')[0].click();
    }

    if (i % 5 === 1) {
      $('#tasks-tab')[0].click();
      setTimeout(() => $(`#tasks-list li:nth-child(${listItemIdx}) a`)[0].click(), itemTimeToWait);
    }

    if (i % 5 === 2) {
      $('#reports-tab')[0].click();
      setTimeout(() => $(`#reports-list li:nth-child(${listItemIdx}) a`)[0].click(), itemTimeToWait);
    }

    if (i % 5 === 3) {
      $('#contacts-tab')[0].click();
      setTimeout(() => $(`#contacts-list li:nth-child(${listItemIdx}) a`)[0].click(), itemTimeToWait);
    }

    if (i % 5 === 4)  {
      $('#analytics-tab')[0].click();
      // load the targets page
      setTimeout(() => $('.mm-navigation-menu li:first-of-type a')[0].click(), itemTimeToWait);
    }

    if (++i > 100) {
      clearInterval(mInterval);
    }
  }, tabTimeToWait);
})();
```
I ran this script for 10 iterations 1st (each page loaded twice) and recorded a "baseline" memory + dom node footprint. 
Than ran 10 iterations 3 times, each time checking the browser performance tab. 

Before: 
image

After:
image

**Comment by dianabarsan** [comment]
hey @njogz 
Please have a look. Thanks!

**Comment by garethbowen** [comment]
That's awesome. Great work!

Do you think it's also worth re-running your load time tests to check if these changes has also noticeably improved or reduced performance?

**Comment by dianabarsan** [comment]
> Do you think it's also worth re-running your load time tests to check if these changes has also noticeably improved or reduced performance?

Yes! Happy to say that my initial load + second load times have **not changed**.

**Review by njogz — APPROVED** [review]
Good job on this! Looks good.

**Pull request merged**
