### PR TITLE
feat(#8660) - add link in conversation to navigate to sender's contact page

### PR DESCRIPTION
**Pull request by latin-panda**
# Description

- Adds link in conversation to navigate to sender's contact page
- Adds unit test
- Adds e2e test - happy path

#8660

# Code review checklist

- [ ] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- [ ] Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- [ ] Tested: Unit and/or e2e where appropriate
- [ ] Internationalised: All user facing text
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# Compose URLs

If Build CI hasn't passed, these may 404:

* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:message-tab-link-to-contact/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:message-tab-link-to-contact/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:message-tab-link-to-contact/docker-compose/cht-couchdb-clustered.yml)

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

### CODE REVIEW

**Comment by latin-panda** [comment]
Hi @tatilepizs @m5r @Benmuiruri, please have a look at this quick fix. Thanks!

**Comment by latin-panda** [comment]
CI is green and this is ready :)

**Review by Benmuiruri — APPROVED** [review]
LGTM! 👍

**Review by m5r — APPROVED** [review]
Looking good! Ship it :rocket:

**Review by tatilepizs — APPROVED** [review]
Thank you Jenny for adding also the automated tests for the feature.
I tested it manually and ran also the test e2e test and everything is working perfectly 🌟

**Pull request merged**
