### PR TITLE
fix (na): explicitly declare "platform: linux/amd64" in Docker Helper for CHT 3.x

### PR DESCRIPTION
**Pull request by mrjones-plip**
# Description

Docker helper 3.x is known to not run on Apple Silicon (eg M1/M2).  This commit hopefully causes docker to explicitly fails early instead of ambiguously hanging

# Code review checklist

- [X] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- [ ] Tested: Unit and/or e2e where appropriate
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# Compose URLs

If Build CI hasn't passed, these may 404:

* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:cht3x-docker-helper-apple-silicon/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:cht3x-docker-helper-apple-silicon/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:cht3x-docker-helper-apple-silicon/docker-compose/cht-couchdb-clustered.yml)

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

### CODE REVIEW

**Comment by garethbowen** [comment]
@mrjones-plip Is this still useful? If so, can you rebase and request review?

**Comment by mrjones-plip** [comment]
@nydr  - are free to test this? I think you have a new Apple Silicon mac yeah?  

Steps to test:
0. be on an Apple Silicon mac 
1. check out this repo and this branch `cht3x-docker-helper-apple-silicon`
2. try and run [docker helper for 3.x](https://docs.communityhealthtoolkit.org/apps/guides/hosting/3.x/app-developer/#cht-docker-helper) 
3. ensure it explicitly fails instead of hanging

**Comment by mrjones-plip** [comment]
thanks for the nudge @garethbowen ! I've updated and put it out for review.

**Comment by mrjones-plip** [comment]
@nydr  - oh no!  Thanks for checking this out.

I'm curious if you have a apple silicon that you tested on or you're going on a hunch?

**Comment by mrjones-plip** [comment]
Not having a Silicon Mac to test on and not having the time to pursue this, I'm going to close the PR.  Anyone else is free to pick it up if they want to try again!

**Pull request closed without merging**
