### PR TITLE
Re-enable facility filter display throttle

### PR DESCRIPTION
**Pull request by dianabarsan**
# Description

Also fixes facility filter display throttle to:
- display as many places necessary to have a scroll from the get-go (to avoid having to open and close the dropdown to get more places if no scroll is displayed)
- not load everything at once on the first scroll event (the scroll event is triggered for every pixel scrolled, so every pixel scrolled was displaying one more facility....)

Removes the last unused js file. 
Removes function call from filter template. 

https://github.com/medic/angular10-migration/issues/10

# Code review checklist

- [ ] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- [ ] Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- [ ] Tested: Unit and/or e2e where appropriate
- [ ] Internationalised: All user facing text
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

### CODE REVIEW

**Comment by dianabarsan** [comment]
300 district_hospitals (no children)
Showcases how the initial load looks like:
https://user-images.githubusercontent.com/35681649/107427318-ef722b00-6b29-11eb-9f12-4e5e853cc478.mp4

300 district_hospitals, each with 200 health_centers
Showcases initial load for a "large" 1st item

https://user-images.githubusercontent.com/35681649/107427767-64456500-6b2a-11eb-9fbe-3210f7502021.mp4

**Comment by dianabarsan** [comment]
Realized above video didn't display the loading part of the filter: 

https://user-images.githubusercontent.com/35681649/107434422-711a8680-6b33-11eb-8e41-723f528ec3ce.mp4

**Comment by dianabarsan** [comment]
By comparison, this is **master**, same scenarios:

https://user-images.githubusercontent.com/35681649/107463655-434f3500-6b67-11eb-9314-9a8988b2f954.mp4


https://user-images.githubusercontent.com/35681649/107463659-464a2580-6b67-11eb-84bb-c757b547ed92.mp4

One can see, at the end, how a single scroll event becomes a little laggy because it queues loading an additional facility for every scrolled pixel.

**Comment by dianabarsan** [comment]
hey @garethbowen , 
mind having a look? Thanks!

**Review by garethbowen — APPROVED** [review]
This looks fine, but I'm concerned we're relying too much on custom code for the common "infinite scroll" pattern. I think we'd be better off using something like [this library](https://www.npmjs.com/package/ngx-infinite-scroll) instead. I'll leave it up to you to decide whether it's worth switching over now or raising an issue to fix it later.

This could also be useful for things like the LHS of each tab, and the messages content.

**Comment by dianabarsan** [comment]
I'm reluctant from adding a new dependency now, especially for such an underused feature, and go through another round of performance tests, 
It does look really promising, however!

**Comment by garethbowen** [comment]
Fair enough! Please raise an issue to investigate at a later date.

**Comment by dianabarsan** [comment]
Done https://github.com/medic/cht-core/issues/6918

**Pull request merged**
