### PR TITLE
Added dev version of docker-compose.yml

### PR DESCRIPTION
**Pull request by garethbowen**
This extends the production version to expose the couchdb port
to make debugging and recovery easier.

medic/cht-core#6455

# Code review checklist

- [ ] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- [ ] Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- [ ] Tested: Unit and/or e2e where appropriate
- [ ] Internationalised: All user facing text
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

### CODE REVIEW

**Comment by garethbowen** [comment]
Review please @mrjones-plip !

You can test this out with this command...

```
docker-compose -f docker-compose.yml -f docker-compose.dev.yml up
```

I'll update the documentation once this change is approved.

**Comment by mrjones-plip** [comment]
Oh! Looks awesome. I'll grab this in the next day or two.

**Comment by mrjones-plip** [comment]
@garethbowen  - running through a quick review, I hit three possible snags, one of which I think we accounted for already? 
1. before starting I checked with `docker ps -a` and saw I had some old IMAGEs which might collide. Indeed, when I first ran `docker-compose` I got the "The container name "/haproxy" is already in use by container" for both `ha-proxy` and for `medic-os`: 
    ```
   ERROR: for haproxy  Cannot create container for service haproxy: Conflict. The container name "/haproxy" is already in use by container "c9a6c2d6127326231dae8848828a70c576721ece3896695b4df567def5cd505d". You have to remove (or rename) that container to be able to reuse that name.
   ```
   I think this likely OK, but worth noting you have some house cleaning before you can start.  If this is a less technical audience, we should be sure to do some hand holding in docs if we suspect they'll have run `docker` for Medic stuffs before. For me two calls to `docker rm DOCKER_ID` fixed it
1. Port collision. I already had stuff running on `80` and `443`.  I can't remember where, but we talked about this before...maybe in a QA repo? Any way error was:
   ```
   ERROR: for medic-os  Cannot start service medic-os: driver failed programming external connectivity on endpoint medic-os (fabdaab6435813e75de857a58150623852a9986261b40213241ab435f1a2912a): Error starting userland proxy: listen tcp4 0.0.0.0:80: bind: address already in use
   ```

   And fix was to remap the ports by editing `docker-compose.yml` for the `medic-os` stanza to read:

   ```
    ports:
    - 8080:80
    - 8443:443
    ```
 1. Finally, I got a fatal error with `ha-proxy` which I haven't dug into, but here's the logs up to the point that it tipped over:
    ```
    ➜  cht-core git:(6455-added-docker-compose-dev) ✗ docker-compose -f docker-compose.yml -f docker-compose.dev.yml up
    Removing medic-os
    Starting haproxy ... done
    Recreating 590470781f4e_medic-os ... done
    Attaching to haproxy, medic-os
    haproxy     | Starting enhanced syslogd: rsyslogd.
    haproxy     | Nov  9 19:18:54 c9a6c2d61273 haproxy[24]: 192.168.176.3,200,GET,/medic-user-medic-meta/_changes?include_docs=true&feed=longpoll&heartbeat=10000&since=12-g1AAAAJjeJyd0V0KwjAMAOC6CfrqCfQEssj6syd3E03ayRhTn3zWm-hN9CZ6k9pZYQ6G0BFIICHfQ1IzxqZlbNhMH0-6NJTDSi4TF1C7UYSM5tbaqoxxtHeNiVFgsoL6Fv4wtHCZ1h0JsiwpFIZKeSNtvlL0kRTiTkoVKm0b6dyRUIBBHiodxi6ziysOu7YamIJTKgdpN6_dW01ITiT0IO3htWd7_VQJI1ToH7328trPLwVHDQn07VVve1efNg&limit=25,-,medic,'-',310,9909,-,'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:82.0) Gecko/20100101 Firefox/82.0'
    haproxy     | Nov  9 19:18:54 c9a6c2d61273 haproxy[24]: 192.168.176.3,200,GET,/medic/_changes?feed=longpoll&heartbeat=10000&since=301-g1AAAAJjeJyd0L0KwkAMAOBDBV1F3ES7OAnS-21vsu_hoJc7SilVJ2d9E30TfRN9k3o_HYvQEkggIR8hFUJoUgwNmurLVRcGMkySbWwDV3Y0UAhWdV2XxVAtTrYxxtrgWOq2hT8MRDbDrpGWXmIACeG8q5Q56dBIMy9RQXmORVfp6KRbI0VeEinDmpiO0nlkM7rbYrGH0zbhLmkoTftpz6C9nDb3mkppLiTrpb2D9nHa2mucKSXtcX20b9D83_ZeA1CcctK2V_4A0kSfVw&limit=25,-,medic,'-',310,9926,-,'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:82.0) Gecko/20100101 Firefox/82.0'
    haproxy     | Nov  9 19:19:23 c9a6c2d61273 haproxy[24]: Stopping frontend http-in in 0 ms.
    haproxy     | Nov  9 19:19:23 c9a6c2d61273 haproxy[24]: Stopping frontend http-in2 in 0 ms.
    haproxy     | Nov  9 19:19:23 c9a6c2d61273 haproxy[24]: Stopping backend couch-backend in 0 ms.
    haproxy     | Nov  9 19:19:23 c9a6c2d61273 haproxy[24]: Stopping backend couch-backend2 in 0 ms.
    haproxy     | Nov  9 19:19:23 c9a6c2d61273 haproxy[24]: Proxy http-in stopped (FE: 13085 conns, BE: 0 conns).
    haproxy     | Nov  9 19:19:23 c9a6c2d61273 haproxy[24]: Proxy http-in2 stopped (FE: 8 conns, BE: 0 conns).
    haproxy     | Nov  9 19:19:23 c9a6c2d61273 haproxy[24]: Proxy couch-backend stopped (FE: 0 conns, BE: 13085 conns).
    haproxy     | Nov  9 19:19:23 c9a6c2d61273 haproxy[24]: Proxy couch-backend2 stopped (FE: 0 conns, BE: 8 conns).
    haproxy     | # Setting `log` here with the address of 127.0.0.1 will have the effect
    haproxy     | # of haproxy sending the udp log messages to its own rsyslog instance
    haproxy     | # (which sits at `127.0.0.1`) at the `local0` facility including all
    haproxy     | # logs that have a priority greater or equal to the specified log level
    haproxy     | # log 127.0.0.1 local0 warning
    haproxy     | global
    haproxy     |   maxconn 4096
    haproxy     |   lua-load /usr/local/etc/haproxy/parse_basic.lua
    haproxy     |   lua-load /usr/local/etc/haproxy/parse_cookie.lua
    haproxy     |   log /dev/log len 65535 local2 info
    haproxy     |
    haproxy     | defaults
    haproxy     |   mode http
    haproxy     |   log global
    haproxy     |   option dontlognull
    haproxy     |   option http-ignore-probes
    haproxy     |   timeout client 150000
    haproxy     |   timeout server 3600000
    haproxy     |   timeout connect 15000
    haproxy     |   stats enable
    haproxy     |   stats refresh 30s
    haproxy     |   stats auth :
    haproxy     |   stats uri /haproxy?stats
    haproxy     |
    haproxy     | frontend http-in
    haproxy     |   bind  *:5984
    haproxy     |   acl has_user req.hdr(x-medic-user) -m found
    haproxy     |   acl has_cookie req.hdr(cookie) -m found
    haproxy     |   acl has_basic_auth req.hdr(authorization) -m found
    haproxy     |   declare capture request len 400000
    haproxy     |   http-request set-header x-medic-user %[lua.parseBasic] if has_basic_auth
    haproxy     |   http-request set-header x-medic-user %[lua.parseCookie] if !has_basic_auth !has_user has_cookie
    haproxy     |   http-request capture req.body id 0 # capture.req.hdr(0)
    haproxy     |   http-request capture req.hdr(x-medic-service) len 200 # capture.req.hdr(1)   
    haproxy     |   http-request capture req.hdr(x-medic-user) len 200 # capture.req.hdr(2)
    haproxy     |   http-request capture req.hdr(user-agent) len 600 # capture.req.hdr(3)
    haproxy     |   capture response header Content-Length len 10 # capture.res.hdr(0)
    haproxy     |   log-format "%ci,%ST,%[capture.req.method],%[capture.req.uri],%[capture.req.hdr(1)],%[capture.req.hdr(2)],'%[capture.req.hdr(0)]',%B,%Tr,%[capture.res.hdr(0)],'%[capture.req.hdr(3)]'"
    haproxy     |   default_backend couch-backend
    haproxy     |
    haproxy     | frontend http-in2
    haproxy     |   bind  *:5986
    haproxy     |   default_backend couch-backend2
    haproxy     |
    haproxy     | backend couch-backend
    haproxy     |   balance roundrobin
    haproxy     |   server couchdb1 medic-os:5985
    haproxy     |
    haproxy     | backend couch-backend2
    haproxy     |   balance roundrobin
    haproxy     |   server couchdb1 medic-os:5987
    medic-os    | mesg: ttyname failed: Inappropriate ioctl for device
    haproxy     | [alert] 054/044805 (1) : parseBasic loaded
    haproxy     | [alert] 054/044805 (1) : parseCookie loaded
    haproxy     | [ALERT] 054/044805 (1) : parsing [/usr/local/etc/haproxy/haproxy.cfg:47] : 'server couchdb1' : could not resolve address 'medic-os'.
    haproxy     | [ALERT] 054/044805 (1) : parsing [/usr/local/etc/haproxy/haproxy.cfg:51] : 'server couchdb1' : could not resolve address 'medic-os'.
    haproxy     | [ALERT] 054/044805 (1) : Failed to initialize server(s) addr.
    haproxy exited with code 1
    medic-os    | [2021/02/24 04:48:06] Info: Setting up software...
    ```

If I'm being daft and missing some obvious docker thing, lemme know.  Or if you wanna pair on this tomorrow to see what what on my local instance, happy to oblige!

Otherwi

**Comment by mrjones-plip** [comment]
@garethbowen  - last night I tested on my desktop (ubuntu 18.04).  This morning I tested on my laptop (Ubuntu 20.04) and had the first two problems, but the the fatal third, so my CHT instance came up after some `docker rm` and remapping ports:

```
➜  ~ docker ps
CONTAINER ID   IMAGE                                 COMMAND                  CREATED         STATUS         PORTS                                         NAMES
61d9e73319c1   medicmobile/medic-os:cht-3.9.0-rc.2   "/bin/bash -l /boot/…"   6 minutes ago   Up 4 minutes   0.0.0.0:8080->80/tcp, 0.0.0.0:8443->443/tcp   medic-os
068ed3f58a0d   medicmobile/haproxy:rc-1.18           "/entrypoint.sh -f /…"   7 minutes ago   Up 4 minutes   0.0.0.0:5984->5984/tcp                        haproxy
```

**Comment by garethbowen** [comment]
@mrjones-plip I've changed the ports, and also changed the couchdb ports for the same reason. Can you please re-review?

**Comment by mrjones-plip** [comment]
@garethbowen - Looks like the `.dev` yaml file isn't overriding the non dev file's ports?  Here's what I get after pulling down this branch with your d19a7b0 commit:

```
docker-compose -f docker-compose.yml -f docker-compose.dev.yml up                                                                               
Removing medic-os                                                                         
Starting haproxy ... done                                                                 
Recreating 6f94495fead6_medic-os ...                                                       
Recreating 6f94495fead6_medic-os ... error                                                     
                                                                                                                                                                                                  
ERROR: for 6f94495fead6_medic-os  Cannot start service medic-os: driver failed programming external connectivity on endpoint medic-os (4aeddeada7f36fd7fe8aec3fa35fdbb5319ecd48d0da97566531e4b0644
e647e): Error starting userland proxy: listen tcp4 0.0.0.0:80: bind: address already in use               
                                                                                                                 
ERROR: for medic-os  Cannot start service medic-os: driver failed programming external connectivity on endpoint medic-os (4aeddeada7f36fd7fe8aec3fa35fdbb5319ecd48d0da97566531e4b0644e647e): Error
 starting userland proxy: listen tcp4 0.0.0.0:80: bind: address already in use
ERROR: Encountered errors while bringing up the project. 
```

I confirmed when I edited ports in `docker-compose.yml` the error went away.

**Comment by mrjones-plip** [comment]
@garethbowen  - per stand up today, here's the [notes from cht-infrastructure for how to work around port conflict](https://github.com/medic/cht-infrastructure/tree/master/self-hosting#port-conflicts) I was thinking of.

**Comment by garethbowen** [comment]
Crud...

> For the multi-value options ports, expose, external_links, dns, dns_search, and tmpfs, Compose concatenates both sets of values:

https://docs.docker.com/compose/extends/#adding-and-overriding-configuration

So the dev version is using both 80 and 8080! Not very helpful.

Now I've removed the ports from the base config and created a `.prod.yml` with 80 and 443. However the dev version is now blocked on being redirected from `http://localhost:8080` -> `https://localhost:80` which I think is the same root cause as #6168 so no need to review this again until that's resolved. I'll just leave this here for now...

**Comment by mrjones-plip** [comment]
@garethbowen  - I know this PR is not active for now, but I was looking at work Nick did in the [nginx-local-ip repo](https://github.com/medic/nginx-local-ip/).  Specifically, he use environment variables in a way I hadn't seen before. I think this is the approach we should take with this PR to expose couchdb ports?

**Comment by garethbowen** [comment]
Let's revisit if this is still needed later.

**Comment by mrjones-plip** [comment]
Closing in favor of #7061

**Pull request closed without merging**
