### PR TITLE
7003-recompile-default-standard-config

### PR DESCRIPTION
**Pull request by meghna-khemka**
Recompile default and standard config after medic-conf patch release

medic/cht-core#7003

# Code review checklist

- [X] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- [X] Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- [X] Tested: Unit and/or e2e where appropriate
- [X] Internationalised: All user facing text
- [X] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

### CODE REVIEW

**Comment by meghna-khemka** [comment]
Since config/default/forms/contact/*.xlsx files need to be ignored, so I have added it to GitIgnore file.
This PR is rework of review comments on [](https://github.com/medic/cht-core/pull/7243).

**Review by newtewt — CHANGES_REQUESTED** [review]
Nice addition to the `.gitignore`. However, these xls files are needed to generate the rest. They need to remain. 

`config/default/forms/contact/PLACE_TYPE-create.xlsx`
`config/default/forms/contact/PLACE_TYPE-edit.xlsx`
`config/default/forms/contact/person-create.xlsx`
`config/default/forms/contact/person-edit.xlsx`

**Review by newtewt — APPROVED** [review]
good to go!

**Review by dianabarsan — APPROVED** [review]
Great work! Thanks for taking this on!

**Pull request merged**
