### PR TITLE
Adds native browser logging to wdio e2e tests

### PR DESCRIPTION
**Pull request by dianabarsan**
# Description

Also stabilizes some intermittently failing e2e tests. 

# Code review checklist

- [ ] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- [ ] Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- [ ] Tested: Unit and/or e2e where appropriate
- [ ] Internationalised: All user facing text
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

### CODE REVIEW

**Comment by dianabarsan** [comment]
Including a sample of the native browser log, which has these caveats:
- All logs, not matter what the level is in the code, gets logged as "INFO" (changing the log level doesn't seem to fix this)
- failed network requests are not logged (changing the log level adds network request logs, but not their "status")


```
~~~~~~~~run-guided-tour~~~~~~~~~~~~
[0812/043449.287946:ERROR:gpu_init.cc(441)] Passthrough is not supported, GL is swiftshader
[0812/043450.114614:INFO:CONSOLE(1)] "User must reauthenticate", source: http://localhost:5988/main.js (1)
[0812/043450.578491:INFO:CONSOLE(1)] "Initiating changes service", source: http://localhost:5988/main.js (1)
[0812/043450.640446:INFO:CONSOLE(1)] "You have administrative privileges; not replicating", source: http://localhost:5988/main.js (1)
[0812/043451.056367:INFO:CONSOLE(1)] "Persistent storage denied: storage may be cleared by the UA under storage pressure.", source: http://localhost:5988/main.js (1)
[0812/043451.095539:INFO:CONSOLE(1)] "The above 404 is totally normal. PouchDB is just detecting if the remote exists.", source: http://localhost:5988/main.js (1)
[0812/043451.202477:INFO:CONSOLE(1)] "RulesEngine Status: Disabled", source: http://localhost:5988/main.js (1)
[0812/043451.508574:INFO:CONSOLE(1)] "Initiating changes watch (meta=false)", source: http://localhost:5988/main.js (1)
[0812/043451.523852:INFO:CONSOLE(1)] "Initiating changes watch (meta=true)", source: http://localhost:5988/main.js (1)
[0812/043452.956975:INFO:CONSOLE(1)] "Bootstrap Tour 'messages' | Step 1 of 7", source: http://localhost:5988/main.js (1)
[0812/043453.533016:INFO:CONSOLE(1)] "Bootstrap Tour 'messages' | Step 2 of 7", source: http://localhost:5988/main.js (1)
[0812/043454.109830:INFO:CONSOLE(1)] "Bootstrap Tour 'messages' | Show the orphan step 3. Orphans option is true.", source: http://localhost:5988/main.js (1)
[0812/043454.116397:INFO:CONSOLE(1)] "Bootstrap Tour 'messages' | Step 3 of 7", source: http://localhost:5988/main.js (1)
[0812/043454.197750:INFO:CONSOLE(1)] "Bootstrap Tour 'messages' | Show the orphan step 4. Orphans option is true.", source: http://localhost:5988/main.js (1)
[0812/043454.210543:INFO:CONSOLE(1)] "Bootstrap Tour 'messages' | Step 4 of 7", source: http://localhost:5988/main.js (1)
[0812/043454.276169:INFO:CONSOLE(1)] "Bootstrap Tour 'messages' | Show the orphan step 5. Orphans option is true.", source: http://localhost:5988/main.js (1)
[0812/043454.282091:INFO:CONSOLE(1)] "Bootstrap Tour 'messages' | Step 5 of 7", source: http://localhost:5988/main.js (1)
[0812/043454.827144:INFO:CONSOLE(1)] "Bootstrap Tour 'messages' | Show the orphan step 6. Orphans option is true.", source: http://localhost:5988/main.js (1)
[0812/043454.831916:INFO:CONSOLE(1)] "Bootstrap Tour 'messages' | Step 6 of 7", source: http://localhost:5988/main.js (1)
[0812/043455.398210:INFO:CONSOLE(1)] "Bootstrap Tour 'messages' | Show the orphan step 7. Orphans option is true.", source: http://localhost:5988/main.js (1)
[0812/043455.410442:INFO:CONSOLE(1)] "Bootstrap Tour 'messages' | Step 7 of 7", source: http://localhost:5988/main.js (1)
[0812/043455.931074:INFO:CONSOLE(1)] "Initiating changes service", source: http://localhost:5988/main.js (1)
[0812/043455.999814:INFO:CONSOLE(1)] "You have administrative privileges; not replicating", source: http://localhost:5988/main.js (1)
[0812/043456.092781:INFO:CONSOLE(1)] "Persistent storage denied: storage may be cleared by the UA under storage pressure.", source: http://localhost:5988/main.js (1)
[0812/043456.213843:INFO:CONSOLE(1)] "Initiating changes watch (meta=false)", source: http://localhost:5988/main.js (1)
[0812/043456.214632:INFO:CONSOLE(1)] "Initiating changes watch (meta=true)", source: http://localhost:5988/main.js (1)
[0812/043456.350687:INFO:CONSOLE(1)] "RulesEngine Status: Disabled", source: http://localhost:5988/main.js (1)
[0812/043457.522244:INFO:CONSOLE(1)] "Bootstrap Tour 'messages' | Tour ended, init prevented.", source: http://localhost:5988/main.js (1)
[0812/043457.531956:INFO:CONSOLE(1)] "Bootstrap Tour 'messages' | Step 1 of 7", source: http://localhost:5988/main.js (1)
[0812/043457.630588:INFO:CONSOLE(1)] "Bootstrap Tour 'messages' | Step 2 of 7", source: http://localhost:5988/main.js (1)
[0812/043458.157683:INFO:CONSOLE(1)] "Bootstrap Tour 'messages' | Show the orphan step 3. Orphans option is true.", source: http://localhost:5988/main.js (1)
[0812/043458.161838:INFO:CONSOLE(1)] "Bootstrap Tour 'messages' | Step 3 of 7", source: http://localhost:5988/main.js (1)
[0812/043458.690019:INFO:CONSOLE(1)] "Bootstrap Tour 'messages' | Show the orphan step 4. Orphans option is true.", source: http://localhost:5988/main.js (1)
[0812/043458.693856:INFO:CONSOLE(1)] "Bootstrap Tour 'messages' | Step 4 of 7", source: http://localhost:5988/main.js (1)
[0812/043459.222918:INFO:CONSOLE(1)] "Bootstrap Tour 'messages' | Show the orphan step 5. Orphans option is true.", source: http://localhost:5988/main.js (1)
[0812/043459.227078:INFO:CONSOLE(1)] "Bootstrap Tour 'messages' | Step 5 of 7", source: http://localhost:5988/main.js (1)
[0812/043459.756382:INFO:CONSOLE(1)] "Bootstrap Tour 'messages' | Show the orphan step 6. Orphans option is true.", source: http://localhost:5988/main.js (1)
[0812/043459.761291:INFO:CONSOLE(1)] "Bootstrap Tour 'messages' | Step 6 of 7", source: http://localhost:5988/main.js (1)
[0812/043500.291763:INFO:CONSOLE(1)] "Bootstrap Tour 'messages' | Show the orphan step 7. Orphans option is true.", source: http://localhost:5988/main.js (1)
[0812/043500.295699:INFO:CONSOLE(1)] "Bootstrap Tour 'messages' | Step 7 of 7", source: http://localhost:5988/main.js (1)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~new-lineage-structure~~~~~~~~~~~~
[0812/043503.020467:ERROR:gpu_init.cc(441)] Passthrough is not supported, GL is swiftshader
[0812/043504.059042:INFO:CONSOLE(1)] "User must reauthenticate", source: http://localhost:5988/main.js (1)
[0812/043504.679928:INFO:CONSOLE(1)] "Initiating changes service", source: http://localhost:5988/main.js (1)
[0812/043504.726593:INFO:CONSOLE(1)] "You have administrative privileges; not replicating", source: http://localhost:5988/main.js (1)
[0812/043504.972616:INFO:CONSOLE(1)] "Persistent storage denied: storage may be cleared by the UA under storage pressure.", source: http://localhost:5988/main.js (1)
[0812/043505.057716:INFO:CONSOLE(1)] "Initiating changes watch (meta=false)", source: http://localhost:5988/main.js (1)
[0812/043505.058947:INFO:CONSOLE(1)] "Initiating changes watch (meta=true)", source: http://localhost:5988/main.js (1)
[0812/043505.192035:INFO:CONSOLE(1)] "RulesEngine Status: Disabled", source: http://localhost:5988/main.js (1)
[0812/043505.983778:INFO:CONSOLE(1)] "Data node: /*/meta/deprecatedID with null-based index: undefined not found. Ignored.", source: http://localhost:5988/main.js (1)
[0812/043506.011989:INFO:CONSOLE(1)] "No active pages found. Make sure your form has at least one relevant input.", source: http://localhost:5988/main.js (1)
[0812/043506.084725:INFO:CONSOLE(1)] "No active pages found. Make sure your form has at least one relevant input.", source: http://localhost:5988/main.js (1)
[0812/043506.854404:INFO:CONSOLE(1)] "No active pages found. Make sure your form has at least one relevant input.", source: http://localhost:5988/main.js (1)
[0812/043507.217544:INFO:CONSOLE(1)] "Attempt to run transitions without initialization", source: http://localhost:5988/main.js (1)
[0812/043507.280664:INFO:CONSOLE(1)] "Contact created", source: http://localhost:5988/main.js (1)
[0812/043508.717562:INFO:CONSOLE(1)] "Data node: /*/meta/deprecatedID with null-based index: undefined not found. Ignored.", source: http://localhost:5988/main.js (1)
[0812/043508.737141:INFO:CONSOLE(1)] "No active pages found. Make sure your form has at least one relevant input.", source: http://localhost:5988/main.js (1)
[0812/043508.795039:INFO:CONSOLE(1)] "No active pages found. Make sure your form has at least one relevant input.", source: http://localhost:5988/main.js (1)
[0812/043509.520196:INFO:CONSOLE(1)] "No active pages found. Make sure your form has at least one relevant input.", source: http://localhost:5988/main.js (1)
[0812/043509.842986:INFO:CONSOLE(1)] "Attempt to run transitions without initialization", source: http://localhost:5988/main.js (1)
[0812/043510.844516:INFO:CONSOLE(1)] "Data node: /*/meta/deprecatedID with null-based index: undefined not found. Ignored.", source: http://localhost:5988/main.js (1)
[0812/043510.860599:INFO:CONSOLE(1)] "No active pages found. Make sure your form has at least one relevant input.", source: http://localhost:5988/main.js (1)
[0812/043510.909262:INFO:CONSOLE(1)] "No active pages found. Make sure your form has at least one relevant input.", source: http://localhost:5988/main.js (1)
[0812/043511.634831:INFO:CONSOLE(1)] "No active pages found. Make sure your form has at least one relevant input.", source: http://localhost:5988/main.js (1)
[0812/043511.957007:INFO:CONSOLE(1)] "Attempt to run transitions without initialization", source: http://localhost:5988/main.js (1)
[0812/043512.971360:INFO:CONSOLE(1)] "Data node: /*/meta/deprecatedID with null-based index: undefined not found. Ignored.", source: http://localhost:5988/main.js (1)
[0812/043513.778215:INFO:CONSOLE(1)] "Attempt to run transitions without initialization", source: http://localhost:5988/main.js (1)
[0812/043513.821410:INFO:CONSOLE(1)] "Contact created", source: http://localhost:5988/main.js (1)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~person-under-area~~~~~~~~~~~~
[0812/043516.631726:ERROR:gpu_init.cc(441)] Passthrough is not supported, GL is swiftshader
[0812/043517.641380:INFO:CONSOLE(1)] "User must reauthenticate", source: http://localhost:5988/main.js (1)
[0812/043518.614092:INFO:CONSOLE(1)] "Initiating changes service", source: http://localhost:5988/main.js (1)
[0812/043518.720131:INFO:CONSOLE(1)] "You have administrative privileges; not replicating", source: http://localhost:5988/main.js (1)
[0812/043518.973505:INFO:CONSOLE(1)] "Persistent storage denied: storage may be cleared by the UA under storage pressure.", source: http://localhost:5988/main.js (1)
[0812/043519.096898:INFO:CONSOLE(1)] "Initiating changes watch (meta=false)", source: http://localhost:5988/main.js (1)
[0812/043519.097988:INFO:CONSOLE(1)] "Initiating changes watch (meta=true)", source: http://localhost:5988/main.js (1)
[0812/043519.167282:INFO:CONSOLE(1)] "RulesEngine Status: Disabled", source: http://localhost:5988/main.js (1)
[0812/043520.264184:INFO:CONSOLE(40643)] "Initiating changes service", source: http://localhost:5988/admin/js/main.js (40643)
[0812/043520.430810:INFO:CONSOLE(40643)] "Initiating changes watch (meta=false)", source: http://localhost:5988/admin/js/main.js (40643)
[0812/043520.430874:INFO:CONSOLE(40643)] "Initiating changes watch (meta=true)", source: http://localhost:5988/admin/js/main.js (40643)
[0812/043521.868559:INFO:CONSOLE(40643)] "Doing Search contacts [object Object] [object Object] undefined", source: http://localhost:5988/admin/js/main.js (40643)
[0812/043523.007991:INFO:CONSOLE(40643)] "Doing Search contacts [object Object] [object Object] undefined", source: http://localhost:5988/admin/js/main.js (40643)
[0812/043523.790827:INFO:CONSOLE(40643)] "CreateUser /api/v1/users [object Object]", source: http://localhost:5988/admin/js/main.js (40643)
[0812/043523.886557:INFO:CONSOLE(40643)] "Change notification firing false [object Object]", source: http://localhost:5988/admin/js/main.js (40643)
[0812/043523.986703:INFO:CONSOLE(40643)] "Change notification firing false [object Object]", source: http://localhost:5988/admin/js/main.js (40643)
[0812/043524.336615:INFO:CONSOLE(40643)] "User must reauthenticate", source: http://localhost:5988/admin/js/main.js (40643)
[0812/043524.392417:INFO:CONSOLE(40643)] "Error watching for db changes TypeError: Failed to fetch", source: http://localhost:5988/admin/js/main.js (40643)
[0812/043524.393789:INFO:CONSOLE(40643)] "Attempting changes reconnection in 5 seconds", source: http://localhost:5988/admin/js/main.js (40643)
[0812/043524.394011:INFO:CONSOLE(40643)] "Error watching for db changes TypeError: Failed to fetch", source: http://localhost:5988/admin/js/main.js (40643)
[0812/043524.394520:INFO:CONSOLE(40643)] "Attempting changes reconnection in 5 seconds", source: http://localhost:5988/admin/js/main.js (40643)
[0812/043527.258061:INFO:CONSOLE(1)] "initialReplication() change [object Object]", source: http://localhost:5988/main.js (1)
[0812/043527.282531:INFO:CONSOLE(1)] "The above 404 is totally normal. PouchDB is just checking if a remote checkpoint exists.", source: http://localhost:5988/main.js (1)
[0812/043527.298682:INFO:CONSOLE(1)] "Initial sync completed successfully in 2.095 seconds", source: http://localhost:5988/main.js (1)
[0812/043527.326154:INFO:CONSOLE(1)] "Not purging: Purge not configured.", source: http://localhost:5988/main.js (1)
[0812/043527.333380:INFO:CONSOLE(1)] "Initiating changes service", source: http://localhost:5988/main.js (1)
[0812/043527.376134:INFO:CONSOLE(1)] "Persistent storage denied: storage may be cleared by the UA under storage pressure.", source: http://localhost:5988/main.js (1)
[0812/043527.557507:INFO:CONSOLE(1)] "Initiating changes watch (meta=false)", source: http://localhost:5988/main.js (1)
[0812/043527.559353:INFO:CONSOLE(1)] "Initiating changes watch (meta=true)", source: http://localhost:5988/main.js (1)
[0812/043527.945344:INFO:CONSOLE(1)] "RulesEngine Status: Enabled", source: http://localhost:5988/main.js (1)
[0812/043528.023889:INFO:CONSOLE(1)] "Error fetching read status [object Object]", source: http://localhost:5988/main.js (1)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~login-logout~~~~~~~~~~~~
[0812/043531.898913:ERROR:gpu_init.cc(441)] Passthrough is not supported, GL is swiftshader
[0812/043532.908148:INFO:CONSOLE(1)] "User must reauthenticate", source: http://localhost:5988/main.js (1)
[0812/043534.073154:INFO:CONSOLE(1)] "Initiating changes service", source: http://localhost:5988/main.js (1)
[0812/043534.161825:INFO:CONSOLE(1)] "You have administrative privileges; not replicating", source: http://localhost:5988/main.js (1)
[0812/043534.372365:INFO:CONSOLE(1)] "Persistent storage denied: storage may be cleared by the UA under storage pressure.", source: http://localhost:5988/main.js (1)
[0812/043534.435483:INFO:CONSOLE(1)] "Initiating changes watch (meta=false)", source: http://localhost:5988/main.js (1)
[0812/043534.441757:INFO:CONSOLE(1)] "Initiating changes watch (meta=true)", source: http://localhost:5988/main.js (1)
[0812/043534.528962:INFO:CONSOLE(1)] "RulesEngine Status: Disabled", source: http://localhost:5988/main.js (1)
[0812/043535.923062:INFO:CONSOLE(1)] "User must reauthenticate", source: http://localhost:5988/main.js (1)
[0812/043536.246816:INFO:CONSOLE(1)] "Initiating changes service", source: http://localhost:5988/main.js (1)
[0812/043536.296980:INFO:CONSOLE(1)] "You have administrative privileges; not replicating", source: http://localhost:5988/main.js (1)
[0812/043536.350642:INFO:CONSOLE(1)] "Persistent storage denied: storage may be cleared by the UA under storage pressure.", source: http://localhost:5988/main.js (1)
[0812/043536.457793:INFO:CONSOLE(1)] "Initiating changes watch (meta=false)", source: http://localhost:5988/main.js (1)
[0812/043536.458309:INFO:CONSOLE(1)] "Initiating changes watch (meta=true)", source: http://localhost:5988/main.js (1)
[0812/043536.487300:INFO:CONSOLE(1)] "RulesEngine Status: Disabled", source: http://localhost:5988/main.js (1)
[0812/043536.850956:INFO:CONSOLE(1)] "User must reauthenticate", source: http://localhost:5988/main.js (1)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~generate-short-codes~~~~~~~~~~~~
[0812/043538.602819:ERROR:gpu_init.cc(441)] Passthrough is not supported, GL is swiftshader
[0812/043539.628566:INFO:CONSOLE(1)] "User must reauthenticate", source: http://localhost:5988/main.js (1)
[0812/043540.797345:INFO:CONSOLE(1)] "Initiating changes service", source: http://localhost:5988/main.js (1)
[0812/043540.866989:INFO:CONSOLE(1)] "You have administrative privileges; not replicating", source: http://localhost:5988/main.js (1)
[0812/043541.088240:INFO:CONSOLE(1)] "Persistent storage denied: storage may be cleared by the UA under storage pressure.", source: http://localhost:5988/main.js (1)
[0812/043541.202687:INFO:CONSOLE(1)] "Initiating changes watch (meta=false)", source: http://localhost:5988/main.js (1)
[0812/043541.205339:INFO:CONSOLE(1)] "Initiating changes watch (meta=true)", source: http://localhost:5988/main.js (1)
[0812/043541.224905:INFO:CONSOLE(1)] "RulesEngine Status: Disabled", source: http://localhost:5988/main.js (1)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~search-contacts~~~~~~~~~~~~
[0812/043545.678445:ERROR:gpu_init.cc(441)] Passthrough is not supported, GL is swiftshader
[0812/043546.711201:INFO:CONSOLE(1)] "User must reauthenticate", source: http://localhost:5988/main.js (1)
[0812/043547.635523:INFO:CONSOLE(1)] "Initiating changes service", source: http://localhost:5988/main.js (1)
[0812/043547.778128:INFO:CONSOLE(1)] "You have administrative privileges; not replicating", source: http://localhost:5988/main.js (1)
[0812/043548.011925:INFO:CONSOLE(1)] "Persistent storage denied: storage may be cleared by the UA under storage pressure.", source: http://localhost:5988/main.js (1)
[0812/043548.142548:INFO:CONSOLE(1)] "Initiating changes watch (meta=false)", source: http://localhost:5988/main.js (1)
[0812/043548.143923:INFO:CONSOLE(1)] "Initiating changes watch (meta=true)", source: http://localhost:5988/main.js (1)
[0812/043548.166168:INFO:CONSOLE(1)] "RulesEngine Status: Disabled", source: http://localhost:5988/main.js (1)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~search-reports~~~~~~~~~~~~
[0812/043553.591205:ERROR:gpu_init.cc(441)] Passthrough is not supported, GL is swiftshader
[0812/043554.588583:INFO:CONSOLE(1)] "User must reauthenticate", source: http://localhost:5988/main.js (1)
[0812/043555.665396:INFO:CONSOLE(1)] "Initiating changes service", source: http://localhost:5988/main.js (1)
[0812/043555.862259:INFO:CONSOLE(1)] "You have administrative privileges; not replicating", source: http://localhost:5988/main.js (1)
[0812/043556.097583:INFO:CONSOLE(1)] "Persistent storage denied: storage may be cleared by the UA under storage pressure.", source: http://localhost:5988/main.js (1)
[0812/043556.212611:INFO:CONSOLE(1)] "RulesEngine Status: Disabled", source: http://localhost:5988/main.js (1)
[0812/043556.396605:INFO:CONSOLE(1)] "Initiating changes watch (meta=false)", source: http://localhost:5988/main.js (1)
[0812/043556.398494:INFO:CONSOLE(1)] "Initiating changes watch (meta=true)", source: http://localhost:5988/main.js (1)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~message-format~~~~~~~~~~~~
[0812/043601.885706:ERROR:gpu_init.cc(441)] Passthrough is not supported, GL is swiftshader
[0812/043602.900654:INFO:CONSOLE(1)] "User must reauthenticate", source: http://localhost:5988/main.js (1)
[0812/043603.615500:INFO:CONSOLE(1)] "Initiating changes service", source: http://localhost:5988/main.js (1)
[0812/043603.696234:INFO:CONSOLE(1)] "You have administrative privileges; not replicating", source: http://localhost:5988/main.js (1)
[0812/043603.968928:INFO:CONSOLE(1)] "Persistent storage denied: storage may be cleared by the UA under storage pressure.", source: http://localhost:5988/main.js (1)
[0812/043604.089101:INFO:CONSOLE(1)] "Initiating changes watch (meta=false)", source: http://localhost:5988/main.js (1)
[0812/043604.094985:INFO:CONSOLE(1)] "Initiating changes watch (meta=true)", source: http://localhost:5988/main.js (1)
[0812/043604.154440:INFO:CONSOLE(1)] "RulesEngine Status: Disabled", source: http://localhost:5988/main.js (1)
[0812/043606.470311:INFO:CONSOLE(1)] "messageformat compile error [object Object]", source: http://localhost:5988/main.js (1)
[0812/043606.473750:INFO:CONSOLE(1)] "Error while interpolating Messages {thing}", source: http://localhost:5988/main.js (1)
[0812/043606.475105:INFO:CONSOLE(1)] "Error while interpolating Messages {thing}", source: http://localhost:5988/main.js (1)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by dianabarsan** [comment]
Tests that are known to fail and are not fixed: 

- Privacy policy for a french offline user 
This test fails because of a bug: https://github.com/medic/cht-core/issues/6960

- mark_for_outbound when external server is up correctly creates and sends an outbound request immediately
This test fails because of a bug: https://github.com/medic/cht-core/issues/6963

**Comment by dianabarsan** [comment]
@newtewt please, pick one

**Review by newtewt — APPROVED** [review]
Nice! Would you think that it's possible to close the tour similar to the snackbar?  As to not hold this up I'm approving

**Comment by dianabarsan** [comment]
Thanks a lot for the review, @newtewt ! 

> Would you think that it's possible to close the tour similar to the snackbar?

The tour is trickier. 
The snackbar html elements are always present in the page, but hidden with CSS (absolute position with negative indexes). 
The tour is a modal, and the html is generated on demand. 
Hiding the tour modal in a similar way would require adding some listener to react to the tour modal opening and hiding it immediately or something similar. 
It's an interesting problem to solve though, I'll think about it. The tour is such a nuisance.

**Comment by dianabarsan** [comment]
I'm merging this. fingers crossed lol.

**Pull request merged**
