### PR TITLE
fix(#9467): better handling of RapidPro error codes

### PR DESCRIPTION
**Pull request by dianabarsan**
# Description

- when api/v2/broadcast responds with 400, set the status as failed, so API doesn't retry sending the same message. This fixes incorrect phone number messages trying to be sent over and over. 
- when api/v2/broadcast responds with 200, but without a status update, set the state to queued to fix message duplication (https://forum.communityhealthtoolkit.org/t/duplication-of-messages-in-textit-rapidpro/4047/19).  

#9467

# Code review checklist

- [ ] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- [ ] Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- [ ] Tested: Unit and/or e2e where appropriate
- [ ] Internationalised: All user facing text
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# Compose URLs
If Build CI hasn't passed, these may 404:

* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9467-update-rapidpro/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9467-update-rapidpro/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9467-update-rapidpro/docker-compose/cht-couchdb-clustered.yml)

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

### CODE REVIEW

**Review by garethbowen — APPROVED** [review]
Looks good to me. I'll make sure this gets a branch release so itech can try it out, and make sure it gets in to the 4.14.0 release.

**Comment by garethbowen** [comment]
We could also handle 403, and 404, more gracefully because both probably require manual intervention to fix so there's no point spamming RapidPro. Even 429s could be handled more gracefully.

But let's raise a new issue to handle these other cases because they're more temporary than the 400 being dealt with here because 400 is permanent failure.

**Comment by lorerod** [comment]
Hi @garethbowen, this looks ready or very close! I can wait to have it included in the 4.14.0 release. Let me know if there's anything else needed before merging.

**Comment by garethbowen** [comment]
@lorerod I'd love to get a [response from Cliff](https://forum.communityhealthtoolkit.org/t/duplication-of-messages-in-textit-rapidpro/4047/46?u=gareth) confirming everything's working, but if he doesn't reply soon let's just merge next week.

**Pull request merged**
