### PR TITLE
feat(#8433): add telemetry events to contact form

### PR DESCRIPTION
**Pull request by Benmuiruri**
# Description

- Adds[ Telemetry Events ](https://docs.communityhealthtoolkit.org/apps/guides/performance/telemetry/) to record Telemetry data in the contact forms 

### Personal Targets

- Each "card" is separated into two content areas
- The content areas is shaded differently to delineate them
- The labels and images which used to be on the top, are now at the lower content area
- Instead of using red for unmet targets, the cards now use black

#8433  

# Code review checklist

- [ ] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- [ ] Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- [ ] Tested: Unit and/or e2e where appropriate
- [ ] Internationalised: All user facing text
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# Compose URLs

If Build CI hasn't passed, these may 404:

- [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:template-issue-update/docker-compose/cht-core.yml)
- [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:template-issue-update/docker-compose/cht-couchdb.yml)
- [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:template-issue-update/docker-compose/cht-couchdb-clustered.yml)

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

### CODE REVIEW

**Comment by Benmuiruri** [comment]
Hi @tatilepizs how to I run the tests that are inside `webapp/tests/karma/ts/` ? 

I want to run the `webapp/tests/karma/ts/modules/reports/reports-add.component.spec.ts` test and see how the test runs because it has some similarities with what I am working on. 

How would I go about running that test. Thank you.

**Comment by tatilepizs** [comment]
Hi @Benmuiruri, 
Sorry but I will not be able to help you with this question, I have never run those tests before and tried to look but didn't find anything useful. A developer will be a better person to help you with this, and I will also learn how to do it 😄

**Comment by garethbowen** [comment]
@Benmuiruri That test can be running locally with the command `npm run unit-webapp`. There are two suites of unit tests in webapp, a mocha one and a karma one, and this command will run both.

**Comment by Benmuiruri** [comment]
> @Benmuiruri That test can be running locally with the command `npm run unit-webapp`. There are two suites of unit tests in webapp, a mocha one and a karma one, and this command will run both.

Thanks @garethbowen , I am back to work today, I will pick up from where I left off with writing the tests.

**Comment by Benmuiruri** [comment]
Closing this pull request because the branch name was causing issues with our CI/CD pipeline. The changes have been moved to a new branch. Please see the new pull request here #8676

**Pull request closed without merging**
