### PR TITLE
feat(#8451) add HTTP/2 & IPv6 support

### PR DESCRIPTION
**Pull request by mrjones-plip**
# Description

This PR:

* adds support for HTTP/2
* adds support for IPv6

To test, use `curl` to get the `http_version` like so:

```bash
curl -o /dev/null -s -w "%{http_version}\n" --http2 https://192-168-68-26.local-ip.medicmobile.org:10450/medic/login
2
```

Above shows `2` because the `GET` was made against a patched nginx instance in docker helper.  Against a non-patched version, this would return `1.1`.  Docker has [support for IPv6](https://docs.docker.com/config/daemon/ipv6/) as well for testing.

medic/cht-core#8451

# Code review checklist

- [X] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- [X] Tested: Unit and/or e2e where appropriate
- [X] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# Compose URLs

If Build CI hasn't passed, these may 404:

* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8451-add-http2-nginx/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8451-add-http2-nginx/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8451-add-http2-nginx/docker-compose/cht-couchdb-clustered.yml)

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

### CODE REVIEW

**Comment by mrjones-plip** [comment]
@garethbowen  - per our chat earlier today, over you to you on how to best test this.  My `curl` one liner isn't that great for validating speed benefits, but maybe is good enough for no regressions and we can test later?  

Otherwise, seems like a great PR for Daniel (not `@` him just yet) based on his know-how of `nginx`!

**Comment by garethbowen** [comment]
FYI the network tab in the browser dev console can also tell you whether it's h1 or h2 but you need to enable the "protocol" column in the settings. curl is good too, but the browser feels like closer to the truth just in case the client is being extra picky...

@mrjones-plip If you have time to spool up your instance and load it up with ~5k docs for a user I'm happy to test from the other side of the world. It's important that we have this comparison to help convince people the upgrade is worth it.

**Comment by garethbowen** [comment]
@mrjones-plip Have you noticed that the wdio tests imploded?

**Comment by mrjones-plip** [comment]
@garethbowen  and tested initially with the `nginx.conf` in this branch and were getting an error in FF:

> Error code: NS_ERROR_NET_INADEQUATE_SECURITY

In chrome it was:

> ERR_HTTP2_INADEQUATE_TRANSPORT_SECURITY 

The fix ended up being upgrading the ciphers from #8278 and this PR. so take a standard `4.2.2` nginx container and swap the `/etc/nginx/nginx.conf` with this:

```
user nginx;
worker_processes auto;

events {
    worker_connections 10240;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile              on;
    keepalive_timeout     3600;
    proxy_read_timeout    3600;
    client_max_body_size  32M;

    server {
        listen         80;
        location ^~ /.well-known/acme-challenge/ {
            default_type "text/plain";
            root /etc/nginx/private/certbot;
        }
        location / {
            return 301 https://$host$request_uri;
        }
    }

    server {
        listen              443 ssl http2;
        listen              [::]:443 ssl http2;

        gzip                on;
        gzip_vary           on;
        gzip_proxied        any;
        gzip_comp_level     6;
        gzip_buffers        16 8k;
        gzip_http_version   1.1;

        gzip_types                  text/plain text/css text/csv text/xml text/javascript
                                    application/json application/x-javascript application/xml
                                    application/vnd.ms-fontobject application/octet-stream
                                    application/x-font-woff multipart/related image/svg+xml;

        ssl_certificate             /etc/nginx/private/cert.pem;
        ssl_certificate_key         /etc/nginx/private/key.pem;
        ssl_prefer_server_ciphers   off;
        ssl_session_timeout         10m;
        ssl_session_cache           shared:SSL:10m;
        ssl_protocols               TLSv1.2 TLSv1.3;
        ssl_ciphers                 ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-CHACHA20-POLY1305;
        ssl_ecdh_curve              secp384r1;
        ssl_session_tickets         off;

        # Prevent "clickjacking" attacks:
        #   This disallows external sites from embedding any of our pages in
        #   an <iframe>. Since medic-reporter currently uses an <iframe>, we've
        #   set the value to SAMEORIGIN instead of DENY. If we ever stop using
        #   <iframes>s, we should probably switch this back to DENY.

        add_header X-Frame-Options  SAMEORIGIN;

        include /etc/nginx/conf.d/server.conf;
    }
}

# vim: set nowrap tw=0:
```

And it all works!

**Comment by garethbowen** [comment]
@mrjones-plip set up an instance on his machine with a user with ~5000 contacts. I tested a few scenarios from my machine on Chromium latest.

First scenario - downloading the app (service worker contents). I disabled cache and wiped application data in Chrome devtools and tested throttled to slow 3g and unthrottled.

h1 throttled: 12.89 seconds
h2 throttled: 12.92 seconds

h1 unthrottled: 3.09 seconds
h2 unthrottled: 2.87 seconds

Second scenario - initial replication. I cleared application data and logged in and timed how long it took to finish rendering.

h1 throttled: 190 seconds
h2 throttled: 198 seconds

h1 unthrottled: 60 seconds
h2 unthrottled: 63 seconds

IMO all of these results are within the margin of error so there's no clear benefit or penalty. This change then falls under "tech debt" or "the right thing to do".

There may be some benefit on flaky connections.

There may be future improvements we can leverage with server push or more parallel connections features.

**Review by nydr — APPROVED** [review]
Great investigation from @mrjones-plip @garethbowen!

> @nydr - I realize I didn't add any tests for HTTP/2 or IPv6 - feel free to push back if you think they're needed!

I don't think additional tests are required as we're not dependent on HTTP/2 streams or operating in any IPv6-only environments. It's relatively easy to add as mentioned above and using something like `curl http://[::1]:1080/` but my local container VM is only configured to forward localhost IPv4 so I have to run tests from the VM, and if more people have a similar configuration then it might be more friction than it's worth. It also seems like some of our existing tests will automatically upgrade to HTTP/2 as mentioned above so that feels like sufficient coverage.

LGTM 👍 (once dependent PR is merged)

**Comment by mrjones-plip** [comment]
great - thanks for the comments @nydr !

**Comment by mrjones-plip** [comment]
@garethbowen  - with #8278 merged to `master`, I merged `master` to this branch in hopes of wdio tests en-imploding.  We'll see!

**Comment by mrjones-plip** [comment]
Wooo hoo!  After many hitings things with the  "re-run failed jobs" hammer, CI passed finally!  

@garethbowen  - feel free to merge or wait for more input or what ever you think is next!

**Pull request merged**
