### PR TITLE
chore(#8929): bump upgrade-service version and helm chart archive

### PR DESCRIPTION
**Pull request by dianabarsan**
# Description

#8929

# Code review checklist

- [ ] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- [ ] Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- [ ] Tested: Unit and/or e2e where appropriate
- [ ] Internationalised: All user facing text
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# Compose URLs
If Build CI hasn't passed, these may 404:

* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8929-upgrade-service-bump/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8929-upgrade-service-bump/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8929-upgrade-service-bump/docker-compose/cht-couchdb-clustered.yml)

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

### CODE REVIEW

**Review by ralfudx — APPROVED** [review]
Hi @dianabarsan i'm going to go ahead to approve this as it's a one liner
I'll update you once I'm able to successfully deploy the multi couchDB instance

**Comment by ralfudx** [comment]
For progress on testing this https://medic.slack.com/archives/C02F2TAME90/p1711444480206659?thread_ts=1710383094.820549&cid=C02F2TAME90

**Comment by dianabarsan** [comment]
@ralfudx do you have any updates on this?

**Comment by ralfudx** [comment]
Hi @dianabarsan I do not have any latest updates on this as I have been swarmed with tasks related to apdex performance tests. However, as part of my deliverables, I have committed to complete this week - kindly expect new updates from tomorrow

**Comment by dianabarsan** [comment]
Closing as obsolete due to https://github.com/medic/cht-core/commit/c6df0362cb6f3cae68bcb711c7bf1d1a5e5f4350 and https://github.com/medic/helm-charts/commit/5a514b193c48c8ff8837198d6b10e2b193d0a749

@ralfudx I believe smoke testing this is still necessary, since this is the primary way we deploy and upgrade production instances.

**Comment by ralfudx** [comment]
Yes @dianabarsan I agree that this still needs to be smoke tested. I've committed to getting the multi-couchDB deployment working for me this week and should complete the test afterwards. I'd provide an update before the end of the week

**Pull request closed without merging**
