### PR TITLE
fix(#8796): log replication counts when users call replication endpoint

### PR DESCRIPTION
**Pull request by dianabarsan**
# Description

Adds replication limit logging back. 

#8796

# Code review checklist

- [ ] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- [ ] Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- [ ] Tested: Unit and/or e2e where appropriate
- [ ] Internationalised: All user facing text
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# Compose URLs

If Build CI hasn't passed, these may 404:

* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8796-record-users-doc-counts/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8796-record-users-doc-counts/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8796-record-users-doc-counts/docker-compose/cht-couchdb-clustered.yml)

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

### CODE REVIEW

**Comment by dianabarsan** [comment]
Hey @latin-panda . I did a whoopsie. Can you please review? Thanks a lot!

**Review by latin-panda — APPROVED** [review]
Nice!! ✨

**Comment by dianabarsan** [comment]
@tatilepizs Would you mind giving this a quick look? Thanks a lot!

**Review by tatilepizs — APPROVED** [review]
Looks good 🌟 

And thank you @dianabarsan because due to this PR I started reading/learning about [`Stubs - Sinon.JS`](https://sinonjs.org/releases/latest/stubs/) that is new to me. 📚

**Pull request merged**
