### PR TITLE
70 sentinel queue tests

### PR DESCRIPTION
**Pull request by ngaruko**
# Description

enabled sentinel queue [ tests](https://github.com/medic/angular10-migration/issues/70)

# Code review items

- Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- Tested: Unit and/or e2e where appropriate
- Internationalised: All user facing text
- Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

### CODE REVIEW

**Comment by newtewt** [comment]
👍  nice work. I think someday we need to find a way to split UI tests and tests that just need API/Sentinel etc. I believe I have seen other tests that do this.  Could speed up some tests that don't need the whole protractor/jasmine/selenium environment.

**Review by newtewt — CHANGES_REQUESTED** [review]
Just need to resolve the conflict with conf.js and you are good to go!

**Comment by ngaruko** [comment]
> Just need to resolve the conflict with conf.js and you are good to go!

Done - was wrong branch merge

**Review by newtewt — APPROVED** [review]
Nice!

**Pull request merged**
