### PR TITLE
Block sentinel access

### PR DESCRIPTION
**Pull request by SCdF**
Only users who have a specific permission or admins should be able to access the sentinel DB.

### CODE REVIEW

**Comment by SCdF** [comment]
> Why did this come about?

I was reading through the code and it seemed wrong to me that online users could access `medic-sentinel`.

> When would we ever want to allow non-admin users access?

If we wanted to correctly configure a restricted couch2pg user would be the most obvious reason. However, I'd be equally OK making it an admin only endpoint if we felt that was better (this would require that the couch2pg user be an admin however).

> Shouldn't this be enforced by the couchdb database security rather than a custom route?

We could definitely look into this. I guess it would be a migration to change the security document to.... expect the `_admin` role? This would lock us into requiring CouchDB admins, which maybe isn't great for the current way we hook into couch2pg.

> Should this be documented with an issue so it can be tested?

PRs can be treated exactly like issues these days AFAICT (you can [link to them as issues](https://github.com/medic/medic/issues/5662), have them in projects, give them labels, assign them etc), so I didn't think we needed to create issues for quick work like this any more.

**Comment by garethbowen** [comment]
> PRs can be treated exactly like issues these days AFAICT (you can link to them as issues, have them in projects, give them labels, assign them etc), so I didn't think we needed to create issues for quick work like this any more.

Using this PR as the issue works for me, but...
- if we want to AT it (and I think we do) it needs to be included in the Project and include steps to reproduce it, and
- and if we want to document the improvement (and I think we do) it needs a more informative title and description and Type and Priority labels.

> We could definitely look into this. I guess it would be a migration to change the security document to.... expect the _admin role? This would lock us into requiring CouchDB admins, which maybe isn't great for the current way we hook into couch2pg.

I would feel more comfortable with this solution. We've made migrations to modify db security before so it should be straightforward. I would have the "_admin" role for "admins" and maybe a new "sentinel" role for "members" - that way we can add the role to a new and improved couch2pg user any time and it'll have read access. We probably need to modify the sentinel db creation script (wherever that is) to create it with the right security in the first place as migrations probably run before creation...

**Comment by garethbowen** [comment]
@SCdF Can we dust this off and get it merged?

**Comment by garethbowen** [comment]
@SCdF ping...

**Comment by SCdF** [comment]
Yeah, sorry mate, it's on a list but so far down it's not going to get seen by me in a long time (it's lower than idbnext lol).

I think I'm going to close this and create a ticket with Help Wanted as it's a good unconnected improvement that anyone could work on.

**Comment by SCdF** [comment]
Ticket raised here: https://github.com/medic/cht-core/issues/6120

**Pull request closed without merging**
