### PR TITLE
fix(#8669): adjusting Enketo label to content

### PR DESCRIPTION
**Pull request by latin-panda**
# Description

- Adjusting Enketo label to content with `display: inline;`

The `display: inline-block;` or `display: block;` doesn't work for long text or fields in columns.

medic/cht-core#8669

# Code review checklist

- [ ] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- [ ] Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- [ ] Tested: Unit and/or e2e where appropriate
- [ ] Internationalised: All user facing text
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# Compose URLs

If Build CI hasn't passed, these may 404:

* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8669-enketo-label-fix/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8669-enketo-label-fix/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8669-enketo-label-fix/docker-compose/cht-couchdb-clustered.yml)

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

### CODE REVIEW

**Comment by latin-panda** [comment]
@tatilepizs I'm adding you again since you have experience with the previous work, this should behave the same as that time. Please see my test evidence below:

<details>
<summary> Short and long text </summary>

Screenshot 2023-10-30 at 3 10 25 pm
Screenshot 2023-10-30 at 3 09 49 pm
Screenshot 2023-10-30 at 3 09 42 pm
Screenshot 2023-10-30 at 3 08 45 pm
Screenshot 2023-10-30 at 3 08 33 pm
Screenshot 2023-10-30 at 3 08 19 pm
</details>

<details>
<summary> Interactive label </summary>

https://github.com/medic/cht-core/assets/66472237/7dafc752-5553-4705-9202-14e70dd7caf2

</details>

<details>
<summary> Normal text in forms with translations </summary>

Screenshot 2023-10-30 at 3 03 39 pm
Screenshot 2023-10-30 at 3 03 28 pm
</details>

**Comment by latin-panda** [comment]
For the record, this same fix passed the CI using the new wdio version (see [here](https://github.com/medic/cht-core/actions/runs/6689991422))

**Comment by dianabarsan** [comment]
Really appreciate the quick turnaround, @latin-panda ! Thanks for being so quick to circle back to this.

**Review by tatilepizs — APPROVED** [review]
It is working perfect.y, thanks @latin-panda ✨ 

<details>
<summary>Images attached</summary>

image
image
image
image
image
image

</details>

**Pull request merged**
