### PR TITLE
Sort reports by reported_date in rules-engine

### PR DESCRIPTION
**Pull request by dianabarsan**
# Description

To make sure that the latest report's emission is picked as winning, sort reports before passing them to nools. 

medic/cht-core#6700

# Code review items

- Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- Tested: Unit and/or e2e where appropriate
- Internationalised: All user facing text
- Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

### CODE REVIEW

**Comment by dianabarsan** [comment]
@garethbowen I wanted to wait for Travis to finish, but it's been 4 hours ... and the build job passed (Travis seems slower for some reason, is the # of concurrent jobs lowered?) 

Would you mind having a look? 
Thanks for your time!

**Review by garethbowen — COMMENTED** [review]
Everything here looks good, thanks for the quick turnaround!

My initial take on this was to add the sorting as late as possible, perhaps in the rules-emitter in the `marshalDocsIntoNoolsFacts` function. This feels less brittle to me because if we change the way we get the reports it won't matter because it's sorted later. Moving it there brings it closer to the contract we're fulfilling - that a fact's reports are sorted by date.

Furthermore, when getting reports for multiple contacts (particularly _all_ contacts), you're sorting the reports against each other, which is doing unnecessary work as the reports are then separated into patient fact arrays. In the worst case if you have 100 contacts each with one report then we're sorting all 100 reports when no sorting is necessary.

Does that make sense? Any problem with that approach?

**Comment by dianabarsan** [comment]
Totally agree, that was my intention actually, and then my mind got side-tracked somehow. Sorry.

**Review by garethbowen — APPROVED** [review]
Great work! Awesome tests, thanks.

I have one small performance hunch, that it would be faster to sort the reports _after_ they've been split into facts, for example, about 5 lines later iterating through the Contacts and sorting all the reports.

I'll approve this anyway so you can decide if you think it should be changed or not.

**Pull request merged**
