### PR TITLE
feat(#6543): add back breadcrumbs for users with many facilities

### PR DESCRIPTION
**Pull request by latin-panda**
# Description

- The scope of this work is breadcrumbs in Reports, Message and Tasks pages. 
- This PR implements the support for when a user has many facility IDs assigned. The rules are:
  - If the user is online, leave breadcrumbs as they are. 
  - If the user is offline but has multiple facilities, leave breadcrumbs as they are. 
  - If the user is offline but only 1 facility is assigned, remove the last piece of the breadcrumb if the name is the same as the user's facility. 
- To assign more than one facility to a user:
  - Go to couchdb, find the `_users` database, find the offline user `org.couchdb:<username>`
  - Make `facility_id` an array and add the IDs: `"facility_id: [ "id-1", "id-2" ]`
      - the facility should be at the same level in the hierarchy. 
  - Go find the `medic` database, find the offline user `org.couchdb:<username>`
  -  Make `facility_id` an array and add the IDs: `"facility_id: [ "id-1", "id-2" ]`. It should match with the one in `_users` db. 

Videos: 
- user with 1 facility (Maggiocester's CHU)
https://github.com/medic/cht-core/assets/66472237/dde98e55-b4fe-4385-8436-5a107f9b8e25

- user with multiple facilities (Maggiocester's CHU, Hodkiewiczland's CHU)
https://github.com/medic/cht-core/assets/66472237/85382e57-d4c7-49e4-baa4-7d29efe55874

#6543

# Code review checklist

- [ ] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- [ ] Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- [ ] Tested: Unit and/or e2e where appropriate
- [ ] Internationalised: All user facing text
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# Compose URLs
If Build CI hasn't passed, these may 404:

* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:breadcrumbs-multi-facility/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:breadcrumbs-multi-facility/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:breadcrumbs-multi-facility/docker-compose/cht-couchdb-clustered.yml)

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

### CODE REVIEW

**Comment by latin-panda** [comment]
I had a quick chat with @lorerod, she will have a look instead of @ralfudx. 
Thanks @lorerod!!

**Comment by latin-panda** [comment]
BTW @lorerod the contacts page is still not working - @Benmuiruri is fixing that in [this other PR](https://github.com/medic/cht-core/pull/9094). 

This job is only about breadcrumbs in Reports, Message and tasks pages. [I have updated the PR decription]

**Review by Benmuiruri — APPROVED** [review]
LGTM!

**Review by lorerod — APPROVED** [review]
LGTM!

**Comment by latin-panda** [comment]
@Benmuiruri, Same here. This has been rebased, and the tests are working. It's ready. Just waiting for [6543-multi-facility](https://github.com/medic/cht-core/tree/6543-multi-facility).

**Pull request merged**
