### PR TITLE
fix breatfeeding typo for delivery form in default config

### PR DESCRIPTION
**Pull request by elvisdorkenoo**
# Description

fix breatfeeding typo in delivery xls form, then update xml form using cht-conf convert and upload commands on the default config.

medic/cht-core#7595

# Code review checklist

- [ ] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- [ ] Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- [ ] Tested: Unit and/or e2e where appropriate
- [ ] Internationalised: All user facing text
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# Compose URLs:

* CHT Core: CHT_CORE_COMPOSE_URL
* CouchDB Single: COUCH_SINGLE_COMPOSE_URL
* CouchDB Cluster: COUCH_CLUSTER_COMPOSE_URL
 
# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

### CODE REVIEW

**Review by dianabarsan — CHANGES_REQUESTED** [review]
Thanks for taking this on. 

I searched the repo and found a few more instances where the `breastfeeding` exists: https://github.com/medic/cht-core/search?q=breatfeeding

I believe all need updating, right?

**Comment by elvisdorkenoo** [comment]
> Thanks for taking this on.
> 
> I searched the repo and found a few more instances where the `breatfeeding` exists: https://github.com/medic/cht-core/search?q=breatfeeding
> 
> I believe all need updating, right?



> Thanks for taking this on.
> 
> I searched the repo and found a few more instances where the `breatfeeding` exists: https://github.com/medic/cht-core/search?q=breatfeeding
> 
> I believe all need updating, right?

Yeah, good catch, you are right ! I took a look through the search result, for the first change, I did use the cht-conf command to update the xml form, but for the rest of the typos I believe that a simple search and replace would do the trick, please what do you think?

**Comment by dianabarsan** [comment]
Search and replace should work, but please examine the changes that were necessary to make sure no additional workflows / tests need edits.

**Review by dianabarsan — APPROVED** [review]
Very nice! Thank you!

**Comment by elvisdorkenoo** [comment]
> Very nice! Thank you!

Thank you for you time !

**Pull request merged**
