### PR TITLE
6972 remove ability to set user language in database

### PR DESCRIPTION
**Pull request by dacar1988**
# Description
This PR removes the language field in the Add User modal in the template` admin/src/js/controllers/edit-user.js` and also removes the related field management in the js file associated `admin/src/js/controllers/edit-user.js`.

Removing this field means that it is not possible to choose a language not only when a user is added but also when is updated. I hope it is fine for you.

medic/cht-core#6972

# Code review checklist

- [ ] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- [ ] Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- [ ] Tested: Unit and/or e2e where appropriate
- [ ] Internationalised: All user facing text
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

### CODE REVIEW

**Comment by dacar1988** [comment]
Hi @garethbowen! Unfortunately I can't tell you what would be the best option. Sorry.

**Comment by garethbowen** [comment]
@dacar1988 Well we need to remove the `language` property from the API and documentation, for example, everywhere `language` is mentioned in the [users service](https://github.com/medic/cht-core/blob/master/api/src/services/users.js).

Do you have the time and inclination to do this? If not, I'm happy to do it as a separate task.

**Comment by dacar1988** [comment]
Hi @garethbowen! I will try to remove the language property from users service in this PR. 
Where can I find instances of language in the documentation? Thanks.

**Comment by dacar1988** [comment]
Hi @garethbowen! Maybe it is better to create a new task, I tried to remove the property `language` in users service but it could be also in other places where I cannot find them and I do not think to have the right knowledge to do that in the best way.

**Comment by garethbowen** [comment]
Thanks @dacar1988 - I've raised a new issue for the API part: https://github.com/medic/cht-core/issues/7068

This is ready for AT.

**Review by garethbowen — APPROVED** [review]

**Pull request merged**
