### PR TITLE
chore: patch release version

### PR DESCRIPTION
**Pull request by Benmuiruri**
# Description

patch version to `4.8.0` as part of release process.

# Code review checklist

- [ ] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- [ ] Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- [ ] Tested: Unit and/or e2e where appropriate
- [ ] Internationalised: All user facing text
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# Compose URLs
If Build CI hasn't passed, these may 404:

* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:bump-version/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:bump-version/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:bump-version/docker-compose/cht-couchdb-clustered.yml)

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

### CODE REVIEW

**Comment by garethbowen** [comment]
@dianabarsan I think this will _just work_ right?

**Comment by dianabarsan** [comment]
Yea, this will just work. we could bump to 4.9.0 fwiw

**Comment by Benmuiruri** [comment]
@dianabarsan your suggestion to bump 4.9.0 will effectively mean we skip releasing 4.8.0. Won't that be odd that there is no 4.8.0 ? 

What concern do you have with proceeding with the 4.8.0 release ?

**Comment by dianabarsan** [comment]
> will effectively mean we skip releasing 4.8.

I don't understand this. We will release from the `4.8.x` branch, not from `master`.

**Comment by Benmuiruri** [comment]
So you mean bumping master to `4.9.0`. then proceed to releasing `4.8.0` from the `4.8.x` branch like its usually done ?

**Comment by latin-panda** [comment]
@Benmuiruri I'm going to try to explain a bit more 
Once the 4.8.x branch is created, the new commits in the `master` branch are intended for version 4.9.
Diana's suggestion is about setting the master's version to 4.9 because, anyway, we already have a 4.8.x branch, and new commits are for 4.9. 

The important thing is that the master shouldn't be behind in version number; it shouldn't be in 4.7, when we are releasing 4.8.  The [ticket you will be working](https://github.com/medic/cht-core/issues/9136 is to mitigate this.

**Comment by Benmuiruri** [comment]
Thanks Jenni, now I understand what Diana meant.

**Comment by Benmuiruri** [comment]
Ready for review @dianabarsan

**Review by dianabarsan — APPROVED** [review]
<3

**Pull request merged**
