### PR TITLE
feat(#9488): show training cards once a day

### PR DESCRIPTION
**Pull request by latin-panda**
# Description

Saves the last viewed date in the local storage, and if the date is before today, then displays the training cards

<details><summary>Test video: Desktop and mobile views</summary> 

https://github.com/user-attachments/assets/916b3a78-3fe1-4443-b64b-92e7c2a9a075

</details>

https://github.com/medic/cht-core/issues/9488

[PR CHT Docs](https://github.com/medic/cht-docs/pull/1612)

# Code review checklist

- [ ] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- [ ] Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- [ ] Tested: Unit and/or e2e where appropriate
- [ ] Internationalised: All user facing text
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# Compose URLs
If Build CI hasn't passed, these may 404:

* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:training-cards-once-a-day/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:training-cards-once-a-day/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:training-cards-once-a-day/docker-compose/cht-couchdb-clustered.yml)

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

### CODE REVIEW

**Comment by latin-panda** [comment]
@Benmuiruri @kapelo, this is ready for review, please have a look

**Comment by latin-panda** [comment]
@kapelo Do you have any feedback for this PR?

**Comment by latin-panda** [comment]
I remembered a case where multiple users share the same device, so I made this feature specific to the username

Test video:

https://github.com/user-attachments/assets/85893893-5c9b-4f0c-bfb9-89ef3e3340e3

**Review by Benmuiruri — APPROVED** [review]
LGTM 🚀

**Pull request merged**
