### PR TITLE
chore: configure dependabot for more dependencies

### PR DESCRIPTION
**Pull request by garethbowen**
# Description

# Code review checklist

- [ ] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- [ ] Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- [ ] Tested: Unit and/or e2e where appropriate
- [ ] Internationalised: All user facing text
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# Compose URLs
If Build CI hasn't passed, these may 404:

* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:dependabot-for-subdirs/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:dependabot-for-subdirs/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:dependabot-for-subdirs/docker-compose/cht-couchdb-clustered.yml)

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

### CODE REVIEW

**Comment by garethbowen** [comment]
@mrjones-plip This has been going fairly well at the top level so this rolls it out to admin, api, sentinel, and webapp subdirs. There's also the shared-libs but I'll cross that bridge another time.

**Comment by mrjones-plip** [comment]
awesome! lemme dive into this on Mon or Tue of next week.

**Review by mrjones-plip — APPROVED** [review]
Yup - I think this is good!

One (non-blocking) question about the use of `@angular*` on line 68 vs `angular*` on line 25 - that was intentional, yes?  Read [the docs](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups) I wasn't quite sure.

I figure worst case after the first Saturday we can tune the PRs that are opened.

**Comment by garethbowen** [comment]
> One (non-blocking) question about the use of @angular* on line 68 vs angular* on line 25 - that was intentional, yes? 

Yes. "admin" is still on angular v1 which uses a different naming strategy for its packages (without the `@`). It's a moot point because there will never be an update to angular v1...

**Pull request merged**
