### PR TITLE
Skip Webapp blocking unit tests

### PR DESCRIPTION
**Pull request by dianabarsan**
# Description

Skip tests with `xit`.

medic/cht-core#7765

# Code review checklist

- [ ] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- [ ] Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- [ ] Tested: Unit and/or e2e where appropriate
- [ ] Internationalised: All user facing text
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

### CODE REVIEW

**Comment by dianabarsan** [comment]
SUMMARY:
✔ 1928 tests completed
ℹ 4 tests skipped

=============================== Coverage summary ===============================
Statements   : 86.49% ( 9946/11500 )
Branches     : 75.85% ( 4074/5371 )
Functions    : 81.17% ( 2423/2985 )
Lines        : 86.03% ( 9062/10534 

https://github.com/medic/cht-core/runs/8203255485?check_suite_focus=true#step:13:6037

**Comment by dianabarsan** [comment]
I opted for skipping, since:
- these tests are not critical
- I didn't find a very quick refactor to make them work
- it's more important to have the 600 tests run on `master`

**Review by latin-panda — APPROVED** [review]
Thanks, I agree, we can leave the ticket open and tomorrow I'll try to fix these unit tests 🤔 I'm not sure yet what happened but I'll research.

**Comment by dianabarsan** [comment]
Cool, thank you!

From what I could tell, [this call](https://github.com/medic/cht-core/blob/master/webapp/tests/karma/ts/services/enketo.service.spec.ts#L1842) causes a page reload, which in turn stops all following tests from running. If I comment those calls, it makes these couple of tests fail, but it allows the other tests to run.

**Pull request merged**
