### PR TITLE
perf(#9019): tiny improvements to reduce loops

### PR DESCRIPTION
**Pull request by latin-panda**
# Description

- Add all the tasks' [emissions fields in the rule engine](https://github.com/medic/cht-core/blob/679b7051aa15488b6c9f3e872145a3b0d433aba8/webapp/src/ts/services/rules-engine.service.ts#L293) to avoid going through the list of data twice. [Tasks list adds](https://github.com/medic/cht-core/blob/679b7051aa15488b6c9f3e872145a3b0d433aba8/webapp/src/ts/modules/tasks/tasks.component.ts#L129): date, overdue and owner. While [contact detail adds](https://github.com/medic/cht-core/blob/679b7051aa15488b6c9f3e872145a3b0d433aba8/webapp/src/ts/services/tasks-for-contact.service.ts#L66) overdue, the calculation is the same.

- Avoid looping twice a list of tasks in contact reducer.

#9019

# Code review checklist

- [ ] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- [ ] Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- [ ] Tested: Unit and/or e2e where appropriate
- [ ] Internationalised: All user facing text
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# Compose URLs
If Build CI hasn't passed, these may 404:

* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:tiny-improments-to-reduce-loops/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:tiny-improments-to-reduce-loops/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:tiny-improments-to-reduce-loops/docker-compose/cht-couchdb-clustered.yml)

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

### CODE REVIEW

**Comment by latin-panda** [comment]
@Benmuiruri I still need to fix 2 more e2e tests, but I would appreciate an early review of this work.

**Comment by latin-panda** [comment]
@Benmuiruri @ralfudx The e2e and unit tests are passing, and the tests have no significant changes. This small refactor should keep the display of tasks and reports on the Task page and Contact page the same. Please have a look. 
Thanks for your time

**Comment by latin-panda** [comment]
@Benmuiruri @ralfudx please remember to provide feedback on this one :)

**Review by ralfudx — APPROVED** [review]
This looks good

**Review by Benmuiruri — APPROVED** [review]
LGTM!

**Pull request merged**
