### PR TITLE
[DRAFT] Standalone admin

### PR DESCRIPTION
**Pull request by dianabarsan**
# Description

Duplicates all webapp files that admin app requires, preserving git line history, and moves them to admin.
Redux files have been "decluttered" to only contain necessary pieces to admin. 
Because the only merge that will preserve this duped history is a merge-commit, this PR won't be merged to master, but will be a place to address eventual requested changes. 

After all requested changes are addressed, a new branch will be created to contain two clean commits, with acceptable commit messages, that will be merged with a merge-commit into master.

# Code review items

- Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- Tested: Unit and/or e2e where appropriate
- Internationalised: All user facing text
- Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

### CODE REVIEW

**Comment by dianabarsan** [comment]
hey @garethbowen . Please ignore the trail of commits, it was a ... work in progress and squashing destroys history. 
Please tell me what you think. Thanks!

**Review by garethbowen — APPROVED** [review]
Phew... I obviously didn't read every line but it looks good in principle.

It's a shame about duplicating the unit test but it'll make more sense as the services diverge.

You renamed a test for some reason: `.../tests/karma/unit/services/format-date.js → ...ts/karma/unit/services/format-date-new.js`

**Comment by dianabarsan** [comment]
>You renamed a test for some reason: .../tests/karma/unit/services/format-date.js → ...ts/karma/unit/services/format-date-new.js
Opps ... I actually forgot to restore the proper name after the dupe!

**Comment by dianabarsan** [comment]
Closing in favor of https://github.com/medic/cht-core/pull/6622

**Pull request closed without merging**
