### PR TITLE
Disabling the Next button when there are validation errors

### PR DESCRIPTION
**Pull request by peter-ochieng**
# Description

Disabling the Next button when there are validation errors

medic/medic#3399

# Code review items

- Readable: Concise, well named, follows the [style guide](https://github.com/medic/medic-docs/blob/master/development/style-guide.md), documented if necessary.
- Documented: Configuration and user documentation on [medic-docs](https://github.com/medic/medic-docs/)
- Tested: Unit and/or e2e where appropriate
- Internationalised: All user facing text
- Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in Changes.md.

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

### CODE REVIEW

**Comment by garethbowen** [comment]
@peter-ochieng There are some build failures. Could you get all the tests to pass and then let me know it's ready for review?

**Comment by garethbowen** [comment]
@peter-ochieng There are still some test failures to fix here before I can review. Can you please have another look?

**Comment by peter-ochieng** [comment]
@garethbowen Sorry for the delay.The issue with the failing test is that Enketo isn't reevaluating the form `Add Family form` at the juncture `genericForm.nextPage(8)` as its supposed to do in order to enable the Next button.
I am doing more investigations on this issue.

**Comment by garethbowen** [comment]
Closing in favour of https://github.com/medic/cht-core/pull/5953

**Pull request closed without merging**
