### PR TITLE
medic/cht-core#6849

### PR DESCRIPTION
**Pull request by joymkimmel**
# Description

Added new cebuano/bisaya (ceb-ph), hiligaynon/ilonggo (hil-ph), and tagalog (tl-ph) bootstrap datepicker files.

medic/cht-core#6849

# Code review items

- Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- Tested: Unit and/or e2e where appropriate
- Internationalised: All user facing text
- Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

### CODE REVIEW

**Comment by joymkimmel** [comment]
One quick comment on this: For Tagalog, Bisaya and Ilonggo you will notice we left the short Weeks 2/3 character lengths in English. This was not a mistake. In the Philippines calendars are most commonly in English (English is actually an official language of the Philippines). Locals in the communities are not used to seeing shortened versions of the full names of the weeks in the respective languages. I have confirmed this with our staff from each region. However, we did shorten the months as that is okay for them.

**Comment by dianabarsan** [comment]
Thanks so much for your contribution @joymkimmel. 
Your build is failing because of an update we have made  to our Travis config recently (https://github.com/medic/cht-core/pull/6830). 

I'll try to find a solution for your build to pass, but if I don't find one quick enough, would you mind if I created a PR myself and cherry picked your commits? 
I think a Github admin could also merge your changes without successful Travis tests, so that could be another solution.

**Comment by joymkimmel** [comment]
no problem, whatever needs to be done to add it. Thanks!

**Comment by dianabarsan** [comment]
Thanks again @joymkimmel . 
Closing in favor of https://github.com/medic/cht-core/pull/6868

**Pull request closed without merging**
