### PR TITLE
fix(#6775): improve default translation

### PR DESCRIPTION
**Pull request by garethbowen**
# Description

[description]

medic/cht-core#6775

# Code review checklist

- [ ] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- [ ] Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- [ ] Tested: Unit and/or e2e where appropriate
- [ ] Internationalised: All user facing text
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# Compose URLs

If Build CI hasn't passed, these may 404:

* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:6775-improve-default-translation/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:6775-improve-default-translation/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:6775-improve-default-translation/docker-compose/cht-couchdb-clustered.yml)

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

### CODE REVIEW

**Comment by garethbowen** [comment]
@michaelkohn Not a big deal but cleaning up some issues and this seemed like an easy one. Issue is assigned to you so picking on you for the review!

**Comment by garethbowen** [comment]
@michaelkohn I don't think it's leftover from then... But for the life of me I cannot remember what it was for. Looking at the code it is only used for showing the message. I think you might also see the message if targets are not configured. I'm happy to remove the feature, but it will mean that any project who had targets configured but disabled, and the tab visible, will have users start seeing the configured targets, but that seems like a bug in the configuration. What do you think?

**Comment by michaelkohn** [comment]
OK thanks for looking into that! Is it even possible to do the "Disable" from cht-conf?

Either way... I'd say if it's pretty quick and easy to remove it, we should do it.

**Comment by garethbowen** [comment]
Yeah you can disable in cht-conf by updating the config, and you really should, rather than just hitting a button in the UI and then next time you push with cht-conf having the setting overwritten...

**Comment by michaelkohn** [comment]
OK... what do you think, is it quick and easy to get rid of the feature altogether?

**Comment by garethbowen** [comment]
I think so... it's on my list to dig into. Thanks the for the push.

**Comment by garethbowen** [comment]
Closing in favour of https://github.com/medic/cht-core/issues/8498

**Pull request closed without merging**
