### PR TITLE
fix(#7670): do not cache generated patient ids

### PR DESCRIPTION
**Pull request by garethbowen**
# Description

This is the minimal fix... I resisted refactoring more to keep the backport easy and safe.

The DB call is quick against a warm view, so I think this is safe to do. If we find it's a limitation we can cache it in a way that's safe in a distributed environment.

An alternative approach would be to keep the ID cache but still check against the DB every time, which would save regenerating IDs every call, but that's the fast bit so I didn't think that optimisation was necessary.

Because we're going to request to the DB every request instead of every 100 requests the chance of finding 0 unused IDs has increased. This means the length of the ID would be increased more frequently which is bad for the user. To compensate I raised the generation size to 200. It's theoretically possible the length will get bumped on the nth request (where n is the size of the set) if it happens to generate random IDs that are already in use. I would prefer this was changed to be deterministic, and the length was bumped only when the total used IDs reached some percentage of available IDs, but I've left this as an exercise for the future.

medic/cht-core#7670

# Code review checklist

- [ ] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- [ ] Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- [ ] Tested: Unit and/or e2e where appropriate
- [ ] Internationalised: All user facing text
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# Compose URLs

If Build CI hasn't passed, these may 404:

* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:7670-reduce-duplicate-ids/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:7670-reduce-duplicate-ids/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:7670-reduce-duplicate-ids/docker-compose/cht-couchdb-clustered.yml)

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

### CODE REVIEW

**Review by dianabarsan — COMMENTED** [review]
This is cool. I have a few thoughts: 
- I'm uncertain about generating 200 ids instead of 100. 
- can we globalize the "used" set so we don't end up re-checking the same id over and over when we're close to eliminating all ids from one "range"? 
- how come this didn't require any change in unit tests?

**Comment by garethbowen** [comment]
> I'm uncertain about generating 200 ids instead of 100.

What's concerning you? Just because it'll take twice as long in CPU time or the query will take longer? I was worried that the length would get bumped too often otherwise. Do you think I should take this further and implement the formula that works out the ratio between used and total IDs and bumps when the ratio gets too high instead of relying on bad luck?

> can we globalize the "used" set so we don't end up re-checking the same id over and over when we're close to eliminating all ids from one "range"?

With a long ID length that means storing tens of thousands of IDs in memory instead of relying on couchdb to cache them correctly. Doing that won't save us any DB lookups (we will still do exactly 1) so the benefit is just that we won't increment the length as early because we're less likely to get 200 used IDs in one batch. If we did ratio suggested above the cache would make more sense because then we would recursively check the db until we found an unused ID. Do you think I should do both?

> how come this didn't require any change in unit tests?

Yeah that concerned me too, so I broke some of the unit tests to prove they were actually running. Basically the unit tests were never checking the caching function, ie there was no test like: `getId(); getId(); db.callCount.equals(1);`

**Comment by dianabarsan** [comment]
> Do you think I should take this further and implement the formula that works out the ratio between used and total IDs and bumps when the ratio gets too high instead of relying on bad luck?

I'd be curious to see what happens when the number of "free" shortcodes closes to 0. I'm worried about requesting with many keys, I think 200 is not extreme though. If we can get an easy formula that reduces lookups, I'm down! 

Re unit tests: can we do a unit test that does the above? And tests the rest of the caching?

**Comment by garethbowen** [comment]
> I'd be curious to see what happens when the number of "free" shortcodes closes to 0. I'm worried about requesting with many keys, I think 200 is not extreme though. If we can get an easy formula that reduces lookups, I'm down!

The formula I was thinking of would be for detecting when the density of used patient IDs was getting high and is really simple to implement. This would then be used to decide when to bump the id length. Until this threshold was reached, we would retry lookups until we found a free ID. It would _increase_ lookups, but _reduce_ the average length of ids which is better for users.

> Re unit tests: can we do a unit test that does the above? And tests the rest of the caching?

Because the caching has been removed I don't know what this would test, ie: the test above would not pass on the PR by design.

**Comment by dianabarsan** [comment]
Thanks a lot for explaining. I was worried that when the density of used ids would increase, we would be stuck on a retry cycle for a significant time, before bumping the length, but I see that we are bumping the length immediately after 1 failed try. 
I think we should be fine as is. Sorry for the confusion!

**Review by dianabarsan — APPROVED** [review]
🚢

**Pull request merged**
