### PR TITLE
Extend add-local-ip-certs-to-docker.sh to install expired and self signed certs

### PR DESCRIPTION
**Pull request by mrjones-plip**
# Description

In working on some debug stuff for [this PR](https://github.com/medic/cht-core/pull/7374), I really wanted an easy way to install self signed and expired certs.  I realized maybe some other people might too!

Better than some other [rando repo](https://github.com/mrjones-plip/mrjones-medic-scratch/blob/main/add-expired-local-ip-certs-to-docker.sh) ;)

Maybe not the right location for this after our efforts in #7413 - happy to move elsewhere if so!

## Testing

I had some issues getting this to work and found this simple test harness really helpful:
1. create a 1 line bash script `checkcert.sh`:
   ```bash
   echo|openssl s_client -servername 127.0.0.1 -connect 127.0.0.1:443 | openssl x509 -noout -dates
   ```
1. make it executable `chmod +x checkcert.sh`
2. run it every half second: `watch -n 0.5 ./checkcert.sh`

This way `openssl` will tell which cert is installed and when it expires.  

Another simple check (because I thought I was going crazy) which I'll add, is a simple way to check the hash of the `crt` and `key` files:
1. create a 1 line bash script `get-hash.sh`:
   ```bash
   docker exec -it medic-os bash -c "md5sum /srv/settings/medic-core/nginx/private/default.*"
   ```
1. make it executable `chmod +x get-hash.sh`
2. run it every half second: `watch -n 0.5 ./get-hash.sh`

The beauty of both solutions is that you can run `docker-compose down&&docker volume rm medic-data&&docker-compose up` and both `watch` commands will happily fail and then succeed across these very destructive docker commands.  `watch` for the win!

## Code review checklist
- [X] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- [X] Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- [X] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

## License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

### CODE REVIEW

**Review by jkuester — APPROVED** [review]
This is super helpful as-is and is also a great reference for anyone needing to recreate similar situations for testing purposes.   

Testing against a local medic-os container spun up via the `docker-helper` (+1 for providing easy test instructions with the PR as well).  Everything worked as expected!

The only minor question I have is if the certs belong in the `release_testing_script` folder or if they should just have their own directory?  (I am honestly not exactly sure what the release_testing_script is for or how it relates to the `add-local-ip-certs-to-docker.sh` script....

**Comment by mrjones-plip** [comment]
Thanks for the review @jkuester !

> The only minor question I have is if the certs belong in the release_testing_script folder or if they should just have their own directory? (I am honestly not exactly sure what the release_testing_script is for or how it relates to the add-local-ip-certs-to-docker.sh script....)

Yeah...this was the big concern I had too.  Thinking it over, at minimum, the test certs should be in their own directory - they don't have anything to do with release testing.  I'll ping @garethbowen - to see where he thinks they should go and sign up for the possible extra work of moving them. Fixed in 6f67ea3cf

**Comment by mrjones-plip** [comment]
@dianabarsan - when you get back from break, can you use your merge to master superpowers? Builds failed 2/4 times, but critically failed the last time.  Only changes are to the bash script and adding new test TLS certs.

Thanks!

**Comment by dianabarsan** [comment]
I used the superpower of restarting the build and got lucky :) 
Happy merging

**Comment by mrjones-plip** [comment]
That IS a superpower - thanks @dianabarsan !

**Comment by mrjones-plip** [comment]
@dianabarsan  - do we need to worry when `master` [fails to build after a merge](https://github.com/medic/cht-core/actions/runs/1659933026)?  If yes, let me know how I can help!

**Comment by dianabarsan** [comment]
It looks like a test flaked, nothing to worry about.

**Pull request merged**
