### PR TITLE
fix(#8939): display of Eketo's or-appearance-list-nolabel

### PR DESCRIPTION
**Pull request by latin-panda**
# Description

- Excludes `or-appearance-list-nolabel` from the style that displays options. 

<details>
<summary>Test video:</summary>

https://github.com/medic/cht-core/assets/66472237/e58ce706-37bd-4b78-917c-eac8c7e070ac

</details>

<details>
<summary>Screenshots mobile</summary>
Screenshot 2024-03-26 at 5 20 17 PM
Screenshot 2024-03-26 at 5 12 07 PM
Screenshot 2024-03-26 at 5 21 23 PM
Screenshot 2024-03-26 at 5 22 28 PM
Screenshot 2024-03-26 at 5 22 21 PM
Screenshot 2024-03-26 at 5 22 12 PM
Screenshot 2024-03-26 at 5 22 01 PM
Screenshot 2024-03-26 at 5 21 53 PM
Screenshot 2024-03-26 at 5 21 40 PM

</details>

#8939

# Code review checklist

- [ ] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- [ ] Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- [ ] Tested: Unit and/or e2e where appropriate
- [ ] Internationalised: All user facing text
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# Compose URLs
If Build CI hasn't passed, these may 404:

* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8939-grid-display-in-forms-broken/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8939-grid-display-in-forms-broken/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8939-grid-display-in-forms-broken/docker-compose/cht-couchdb-clustered.yml)

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

### CODE REVIEW

**Comment by latin-panda** [comment]
@jkuester @ralfudx This fix is tiny, but most of the job here is testing the options in each question is okay, I have included screenshots and a video in the PR's description box

**Review by jkuester — APPROVED** [review]
Looks good!  I have done a side-by-side comparison of this change with the following forms from support-scripts and did not see any differences!  LGMT

- enketo_widgets
- base64-image
- child-from-repeat-group
- countdown-timer
- date-input
- dynamic-url
- external-data
- format-date
- jr-choice-name
- multiple-repeats
- no-choice-name
- non-relevant-first-page
- output-initial
- multimedia
- multimedia-repeats

**Comment by latin-panda** [comment]
Hi @ralfudx is it okay if I merge?

**Comment by latin-panda** [comment]
@ralfudx Since you won't be able to review this in a while, I went ahead and merged it to keep things going; Josh and I tested the feature well, and it's been documented in this PR. If you have any additional feedback, I can open a new PR to address it

**Pull request merged**
