### PR TITLE
wait for submit button to disappear

### PR DESCRIPTION
**Pull request by ngaruko**
# Description

Fixing flaky test breaking master builds

medic/cht-core#[number]

# Code review checklist

- [ ] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- [ ] Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- [ ] Tested: Unit and/or e2e where appropriate
- [ ] Internationalised: All user facing text
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

### CODE REVIEW

**Review by newtewt — APPROVED** [review]
👍

**Comment by newtewt** [comment]
Simple change nice. Just need the build to pass.

**Comment by meghna-khemka** [comment]
Approved. Build need to be passed before merging.

**Review by meghna-khemka — APPROVED** [review]
Approved.Build need to be passed before merging.

**Pull request merged**
