### PR TITLE
chore(#8757): Remove standard config

### PR DESCRIPTION
**Pull request by mrjones-plip**
# Remove standard config

per #8757 and [slack thread](https://medic.slack.com/archives/C024KTGRW/p1702486854914149):
* deletes all of the config
* replaces it with a single readme
* see [new readme](https://github.com/medic/cht-core/blob/8757-remove-standard-config/config/standard/readme.md) (also in this PR of course, but it's hard to see in the 100s of files changed!)
 
# Code review checklist

- [X] Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)

# Compose URLs

If Build CI hasn't passed, these may 404:

* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8757-remove-standard-config/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8757-remove-standard-config/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8757-remove-standard-config/docker-compose/cht-couchdb-clustered.yml)

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

### CODE REVIEW

**Comment by mrjones-plip** [comment]
We have a large number of reviewers to ensure we're not moving too fast and breaking something.  If you don't have any input, please approve or remove yourself as a reviewer - thanks!

**Comment by mrjones-plip** [comment]
This PR may be blocked by #8758 if this config we're deleting causes CI to fail.  @tatilepizs likely has good ideas around this!

**Comment by tatilepizs** [comment]
Thank you @mrjones-plip for deleting all of those files.  ⭐ 

We need to also remove all the tests related to `standard`, because they depend on the config. I might be missing something, but I think that this is what we need to do:

- [tests/e2e/cht-form/standard](https://github.com/medic/cht-core/tree/8757-remove-standard-config/tests/e2e/cht-form/standard) - Delete the complete folder
- [tests/e2e/standard](https://github.com/medic/cht-core/tree/8757-remove-standard-config/tests/e2e/standard) - Delete the complete folder
- [tests/page-objects/standard](https://github.com/medic/cht-core/tree/8757-remove-standard-config/tests/page-objects/standard) - Delete the complete folder
- [tests/e2e/default/enketo/pregnancy-visit.wdio-spec.js](https://github.com/medic/cht-core/blob/8757-remove-standard-config/tests/e2e/default/enketo/pregnancy-visit.wdio-spec.js) - This test needs to be `skipped` for now, because for some reason it is uploading the form from the `standard` config. We need to fix it, there is already a ticket created to do that -> #8603. 
- [package.json](https://github.com/medic/cht-core/blob/8757-remove-standard-config/package.json) - Remove the lines related with the standard test execution:
  - [wdio-standard-local](https://github.com/medic/cht-core/blob/8757-remove-standard-config/package.json#L50)
  - [ci-webdriver-standard](https://github.com/medic/cht-core/blob/8757-remove-standard-config/package.json#L58)
  - [test-config-standard](https://github.com/medic/cht-core/blob/8757-remove-standard-config/package.json#L61)
- [.github/workflows/build.yml](https://github.com/medic/cht-core/blob/8757-remove-standard-config/.github/workflows/build.yml) - Remove the sections related with the standard e2e tests:
  - ['test-config-standard'](https://github.com/medic/cht-core/blob/8757-remove-standard-config/.github/workflows/build.yml#L82C15-L82C37)
  - [ci-webdriver-standard](https://github.com/medic/cht-core/blob/8757-remove-standard-config/.github/workflows/build.yml#L122C16-L122C37)

**Review by tatilepizs — CHANGES_REQUESTED** [review]
Thank you @mrjones-plip for deleting all of those files.  ⭐ 

We need to also remove all the tests related to `standard`, because they depend on the config. I might be missing something, but I think that this is what we need to do:

- [tests/e2e/cht-form/standard](https://github.com/medic/cht-core/tree/8757-remove-standard-config/tests/e2e/cht-form/standard) - Delete the complete folder
- [tests/e2e/standard](https://github.com/medic/cht-core/tree/8757-remove-standard-config/tests/e2e/standard) - Delete the complete folder
- [tests/page-objects/standard](https://github.com/medic/cht-core/tree/8757-remove-standard-config/tests/page-objects/standard) - Delete the complete folder
- [tests/e2e/default/enketo/pregnancy-visit.wdio-spec.js](https://github.com/medic/cht-core/blob/8757-remove-standard-config/tests/e2e/default/enketo/pregnancy-visit.wdio-spec.js) - This test needs to be `skipped` for now, because for some reason it is uploading the form from the `standard` config. We need to fix it, there is already a ticket created to do that -> #8603. 
- [package.json](https://github.com/medic/cht-core/blob/8757-remove-standard-config/package.json) - Remove the lines related with the standard test execution:
  - [wdio-standard-local](https://github.com/medic/cht-core/blob/8757-remove-standard-config/package.json#L50)
  - [ci-webdriver-standard](https://github.com/medic/cht-core/blob/8757-remove-standard-config/package.json#L58)
  - [test-config-standard](https://github.com/medic/cht-core/blob/8757-remove-standard-config/package.json#L61)
- [.github/workflows/build.yml](https://github.com/medic/cht-core/blob/8757-remove-standard-config/.github/workflows/build.yml) - Remove the sections related with the standard e2e tests:
  - ['test-config-standard'](https://github.com/medic/cht-core/blob/8757-remove-standard-config/.github/workflows/build.yml#L82C15-L82C37)
  - [ci-webdriver-standard](https://github.com/medic/cht-core/blob/8757-remove-standard-config/.github/workflows/build.yml#L122C16-L122C37)

**Comment by mrjones-plip** [comment]
@tatilepizs  - your feedback was so explicit and so helpful - it made for very easy work - thank you!  I've done it all in f5cd395fc 

My biggest concern is that I didn't know how to skip a test, so I copied the way we do it in `e2e/default/enketo/submit-default-delivery-form.wdio-spec.js`, please let me know if I [did it correctly](https://github.com/medic/cht-core/pull/8762/files#diff-1000b0ccdf32c5edd4fc24b24605bd031f6cfb4ff15cc749cde4b261163d0cf1R9).

thanks again!!

**Comment by mrjones-plip** [comment]
@garethbowen @dianabarsan and @kennsippell (as Derick is out for most of January): I haven't heard back from y'all, so I'm going to assume this is all OK with you.  Once I finish up implementing @tatilepizs's changes and the build passes, we'll merge to `master` without waiting for your explicit review approval.

**Comment by garethbowen** [comment]
The standard config is (I think) the only one that uses the test harness, so by removing this we are also no longer testing test harness integration. It might be worth considering writing some basic test harness tests for one of the other configs to make sure we don't regress on test harness support somehow.

I'm slightly nervous about this but I think that's mostly due to the significant time and effort that was put in to generating the config in the first place which is not a good reason to have it hold us back now. Worst case scenario someone will complain and we can revive it later.

Let's do it.

**Comment by latin-panda** [comment]
> The standard config is (I think) the only one that uses the test harness, so by removing this we are also no longer testing test harness integration.

The covid-19 config has [tests with harness](https://github.com/medic/cht-core/tree/master/config/covid-19/test)

**Comment by garethbowen** [comment]
Awesome! That's for pointing that out. It's also using a modern harness so much better than the standard tests.

**Review by tatilepizs — CHANGES_REQUESTED** [review]
Thank you @mrjones-plip for all the updates ⭐ 
 
I think that we are only missing these changes:
- [package.json](https://github.com/medic/cht-core/blob/8757-remove-standard-config/package.json) - Remove the lines related with the standard test execution:
  - [wdio-standard-local](https://github.com/medic/cht-core/blob/8757-remove-standard-config/package.json#L50)
  - [ci-webdriver-standard](https://github.com/medic/cht-core/blob/8757-remove-standard-config/package.json#L58)
  - [test-config-standard](https://github.com/medic/cht-core/blob/8757-remove-standard-config/package.json#L61)
- [.github/workflows/build.yml](https://github.com/medic/cht-core/blob/8757-remove-standard-config/.github/workflows/build.yml) - Remove the sections related with the standard e2e tests:
  - ['test-config-standard'](https://github.com/medic/cht-core/blob/8757-remove-standard-config/.github/workflows/build.yml#L82C15-L82C37)
  - [ci-webdriver-standard](https://github.com/medic/cht-core/blob/8757-remove-standard-config/.github/workflows/build.yml#L122C16-L122C37)

Do we need to wait for something else to remove it from those config files?

**Comment by mrjones-plip** [comment]
ah - good catch - thanks @tatilepizs ! I'd been working in a sub-directory so accidentally didn't commit these.  See 8e66fcffd  for requested changes.

**Comment by mrjones-plip** [comment]
so the change we made skip the test here:

> [tests/e2e/default/enketo/pregnancy-visit.wdio-spec.js](https://github.com/medic/cht-core/blob/8757-remove-standard-config/tests/e2e/default/enketo/pregnancy-visit.wdio-spec.js) - This test needs to be skipped for now, because for some reason it is uploading the form from the standard config. We need to fix it, there is already a ticket created to do that

are not working because before the `describe.skip()` it's still requiring a file which then requires a file which doesn't exist:

```
[0-8] Helper files that use other `browser` commands have to be moved to `before` hook.
[0-8] Spec file(s): file:///home/runner/work/cht-core/cht-core/tests/e2e/default/enketo/pregnancy-visit.wdio-spec.js
[0-8] Error: Error: ENOENT: no such file or directory, open '/home/runner/work/cht-core/cht-core/tests/page-objects/default/enketo/../../../../config/standard/forms/app/pregnancy_visit.xml'
[0-8]     at Object.openSync (node:fs:590:3)
[0-8]     at Object.readFileSync (node:fs:458:35)
[0-8]     at Object.<anonymous> (/home/runner/work/cht-core/cht-core/tests/page-objects/default/enketo/pregnancy-visit.wdio.page.js:4:20)
[0-8]     at Module._compile (node:internal/modules/cjs/loader:1198:14)
[0-8]     at Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
[0-8]     at Object.require.extensions.<computed> [as .js] (/home/runner/work/cht-core/cht-core/node_modules/ts-node/src/index.ts:1608:43)
[0-8]     at Module.load (node:internal/modules/cjs/loader:1076:32)
[0-8]     at Function.Module._load (node:internal/modules/cjs/loader:911:12)
[0-8]     at Module.require (node:internal/modules/cjs/loader:1100:19)
[0-8]     at require (node:internal/modules/cjs/helpers:119:18)
[0-8]     at MochaAdapter._loadFiles (file:///home/runner/work/cht-core/cht-core/node_modules/@wdio/mocha-framework/build/index.js:84:35)
[0-8]     at async MochaAdapter.init (file:///home/runner/work/cht-core/cht-core/node_modules/@wdio/mocha-framework/build/index.js:62:9)
[0-8]     at async Object.adapterFactory.init (file:///home/runner/work/cht-core/cht-core/node_modules/@wdio/mocha-framework/build/index.js:215:22)
[0-8]     at async Runner.run (file:///home/runner/work/cht-core/cht-core/node_modules/@wdio/runner/build/index.js:74:27)
[0-8]  Error:  Unable to load spec files quite likely because they rely on `browser` object that is not fully initialised.
`browser` object has only `capabilities` and some flags like `isMobile`.
```

I've tried moving moving the requires inside the skip function that lets the build pass (see ba1a88f10).  However, I'm not the sharpest JS tool in the shed!

**Comment by mrjones-plip** [comment]
no go!  Trying a different approach in e4fd3e6fa  .

**Comment by mrjones-plip** [comment]
Nope - approach in https://github.com/medic/cht-core/commit/e4fd3e6fadd4ffb6a371c4380092216b3047e55b . failed as well (`error  'pregnancyVisitForm' is not defined  no-undef` - makes sense!)

We'll have to figure a more subtle way to get this tomorrow.

**Comment by tatilepizs** [comment]
@mrjones-plip I did [this commit](https://github.com/medic/cht-core/pull/8762/commits/2abbc8a0aaad2e6006b9a3603a422325df8caac8) and it already passed the first two jobs, I hope it is ok that I did a commit in your PR 😅

**Comment by mrjones-plip** [comment]
Awesome - that's great - thank you! Build is looking good.

**Comment by tatilepizs** [comment]
This is what I was trying to explain in our call earlier 😅 

image

I think that we need help from @garethbowen o from anyone that has the right access to remove those jobs

**Review by tatilepizs — APPROVED** [review]
It looks great, thanks a lot @mrjones-plip for all the updates! 🌟

**Comment by mrjones-plip** [comment]
Ah - thanks @tatilepizs !  

I think with Gareth on holiday, maybe @dianabarsan or @craig-landry  can help maybe? See [above](https://github.com/medic/cht-core/pull/8762#issuecomment-1883593589), but we need to remove the two CI `Expected — Waiting for status to be reported` errors blocking this build from passing.

**Comment by tatilepizs** [comment]
Oh wait, I just found that we need to update also these two files related to testing, we can do it in a separate PR or just do a quick update for those two files, what do you think?

- [TESTING.md](https://github.com/medic/cht-core/blob/8757-remove-standard-config/TESTING.md)
- [AUTOMATE_TEST_GUIDE.md](https://github.com/medic/cht-core/blob/8757-remove-standard-config/tests/AUTOMATE_TEST_GUIDE.md)

**Comment by mrjones-plip** [comment]
I'd say update them here in this PR - that way all the related changes are in one spot. 

Go for it!

**Comment by tatilepizs** [comment]
Done @mrjones-plip, I updated the files 😊 
Everything is green, we just need to remove the expected jobs and we will be ready 🚀

**Pull request merged**
