### PR TITLE
Use the locale cookie to set the language

### PR DESCRIPTION
**Pull request by garethbowen**
medic/cht-core#7617

# Code review checklist

- [ ] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- [ ] Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- [ ] Tested: Unit and/or e2e where appropriate
- [ ] Internationalised: All user facing text
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

### CODE REVIEW

**Comment by garethbowen** [comment]
Review please @latin-panda 

We should fix this in 4.0.0 but it may also be useful to merge it in to your FR branch for your workshop next week.

**Comment by mrjones-plip** [comment]
@dianabarsan  - @latin-panda requested [to be taken off this PR](https://medic.slack.com/archives/C02GME3BQE6/p1651780616318339?thread_ts=1651779163.329629&cid=C02GME3BQE6), so I removed her.  She's heads down on #7503 for the deadline at the end of this week. After that she's taking a vacation, so is doubly not good to be on this.

**Comment by garethbowen** [comment]
@dianabarsan I choose you! No hurry - the FR work is done. This is just a small improvement to get in to 4.0.0 some time.

**Review by dianabarsan — APPROVED** [review]
Nice! My only concern is about not offering a way to change the display language in the admin app.

**Comment by mrjones-plip** [comment]
I think we should block releasing this until we have a good default UX for this. As it stands, if you're in French and upgrade to 4.0, in which this feature is on with no way to turn it off, your admin UI changes in very unexpected ways:

image

We started to [track the translations needed to support French](https://docs.google.com/spreadsheets/d/1sWhyS54ILrEfjZimkmalq8TZZwrnkWG3awzJ6L1DI3o/edit#gid=0) (Medic Google Sheets link).

Deferring to @dianabarsan  and @garethbowen  if you agree though!

**Comment by garethbowen** [comment]
@mrjones-plip I think the experience with incomplete translations for French is the same in the CHT webapp. For example, if a CHW picks French on the login page, and the project hasn't configured the missing translations then the experience is the same. This is by no means acceptable, but it's the current state of affairs - it is _possible_ to configure translations for any language you like, but only English is completely translated out of the box.

> this feature is on with no way to turn it off

The workaround is to disable the language so users can't pick it. The limitation to this approach is you cannot enable the language for the webapp and disable it for the admin app.

I think this change is still a net positive - with this projects can choose to either disable French, or complete the translation values themselves.

**Comment by mrjones-plip** [comment]
Awesome - thanks for the feedback @garethbowen !

**Comment by garethbowen** [comment]
> offering a way to change the display language in the admin app.

I was thinking about just doing this but it's a little fiddly and didn't want to block this improvement so I created a new issue for it: #7625

**Pull request merged**
