### PR TITLE
fix(na): update z_release_major.md forum post template

### PR DESCRIPTION
**Pull request by michaelkohn**
Updated the forum post template when releasing.

### CODE REVIEW

**Comment by michaelkohn** [comment]
> Is this a copy and paste job from the docs release notes?

I think most of the content is coming from the release notes, though it is obviously in a bit different format. If it's possible to automagically populate the forum post template with content from the release notes, that'd be cool!

**Comment by mrjones-plip** [comment]
gotcha!  let's not overthink this and just go for the change - we're iterating so quickly on releases that we'll know if we need to change it or not soon!

**Review by mrjones-plip — APPROVED** [review]

**Comment by mrjones-plip** [comment]
whoa!! are you a GH admin @michaelkohn ?!  CI wasn't passing and i didn't think you could merge to `master` without passing CI?!

image

**Comment by michaelkohn** [comment]
¯\_(ツ)_/¯

No clue!

**Pull request merged**
