### PR TITLE
fix(#8131): display training cards after accepting privacy policies

### PR DESCRIPTION
**Pull request by dianabarsan**
# Description

#8131

# Code review checklist

- [ ] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- [ ] Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- [ ] Tested: Unit and/or e2e where appropriate
- [ ] Internationalised: All user facing text
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# Compose URLs

If Build CI hasn't passed, these may 404:

* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8131-delay-training-cards-popup/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8131-delay-training-cards-popup/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8131-delay-training-cards-popup/docker-compose/cht-couchdb-clustered.yml)

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

### CODE REVIEW

**Comment by dianabarsan** [comment]
Hi @jkuester ! Since you've got your hands dirty quite recently with Angular, would you mind reviewing this fix? Thanks!

**Comment by jkuester** [comment]
@dianabarsan Sorry for the delay!  My goal is to review this tomorrow!

**Comment by dianabarsan** [comment]
No worries! I realized days later after requesting the review that people were offline for holidays! No hurry with this one, thanks for the acknowledgment!

**Review by jkuester — APPROVED** [review]
Clean, simple, easy to follow!  Thanks!  

I tried the behavior locally on my machine and can confirm that it works as expected!

**Pull request merged**
