### PR TITLE
reorder hamburger menu, move sync to top

### PR DESCRIPTION
**Pull request by elvisdorkenoo**
# Description

Partners have reported that users are accidentally logging themselves out when attempting to sync and then are unable to log back in.
So we moved sync component to top.

medic/cht-core#7900

# Code review checklist

- [ ] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- [ ] Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- [ ] Tested: Unit and/or e2e where appropriate
- [ ] Internationalised: All user facing text
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# Compose URLs

If Build CI hasn't passed, these may 404:

* [Core](https://staging.dev.medicmobile.org/_couch/builds/medic:medic:7900-reorder-hamburger-menu/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds/medic:medic:7900-reorder-hamburger-menu/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds/medic:medic:7900-reorder-hamburger-menu/docker-compose/cht-couchdb-clustered.yml)
 
# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

### CODE REVIEW

**Review by jkuester — APPROVED** [review]
:rocket:

**Comment by lorerod** [comment]
Thanks @elvisdorkenoo this looks great! The most used element has to be the first because it is the first thing you focus on when opening the menu. And then the last one. It is perfect.

**Review by lorerod — APPROVED** [review]
Thanks @elvisdorkenoo this looks great! The most used element has to be the first because it is the first thing you focus on when opening the menu. And then the last one. It is perfect.

**Comment by michaelkohn** [comment]
Are the updates to the docs site somewhere else? I would have expected an update here: https://docs.communityhealthtoolkit.org/apps/concepts/navigation/#the-menu-drawer

**Pull request merged**
