### PR TITLE
chore(#8270): add new config for demo environment

### PR DESCRIPTION
**Pull request by michaelkohn**
# Description

Direct copy of `default` config into `demo` folder, no other changes have been made yet. The `demo` folder will be used to maintain configurations on the CHT demo environment.  

https://github.com/medic/cht-core/issues/8270

# Code review checklist

- [ ] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- [ ] Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- [ ] Tested: Unit and/or e2e where appropriate
- [ ] Internationalised: All user facing text
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# Compose URLs

If Build CI hasn't passed, these may 404:

* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8270-update-demo-environment/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8270-update-demo-environment/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8270-update-demo-environment/docker-compose/cht-couchdb-clustered.yml)

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

### CODE REVIEW

**Review by garethbowen — APPROVED** [review]
Thanks!

**Comment by dianabarsan** [comment]
@michaelkohn is there any work pending on this? If not, is it safe to merge once CI passes?

**Comment by dianabarsan** [comment]
I think your test build was very old and got deleted by recurrent cleanup. I launched the whole suite again.

**Comment by garethbowen** [comment]
Rebased and force pushed to run the new builds.

**Pull request merged**
