### PR TITLE
chore(#8435): fix contact age in standard contact summary test

### PR DESCRIPTION
**Pull request by dianabarsan**
# Description

The child was too old for growth monitoring. 

medic/cht-core#8435

# Code review checklist

- [ ] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- [ ] Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- [ ] Tested: Unit and/or e2e where appropriate
- [ ] Internationalised: All user facing text
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# Compose URLs

If Build CI hasn't passed, these may 404:

* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8435-fix-standard-nutrition/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8435-fix-standard-nutrition/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8435-fix-standard-nutrition/docker-compose/cht-couchdb-clustered.yml)

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

### CODE REVIEW

**Comment by dianabarsan** [comment]
Hi @jkuester . Would you mind reviewing this tiny PR? Tests are failing in `master` and all branches right now.

**Review by jkuester — APPROVED** [review]
Awww little Test Child2 is all grown up!  :smiling_face_with_tear:

**Review by garethbowen — APPROVED** [review]
Approved to unblock dev... but maybe we need to set the age dynamically?

**Comment by dianabarsan** [comment]
> Approved to unblock dev... but maybe we need to set the age dynamically?

My guess is that once someone goes into standard config tests, there will be many things that would deserve updating. I'm abstaining :) 
Thanks for the approval!

**Pull request merged**
