### PR TITLE
fix(#9117): use correct _users database name

### PR DESCRIPTION
**Pull request by dianabarsan**
# Description

#9117 

# Code review checklist

- [ ] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- [ ] Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- [ ] Tested: Unit and/or e2e where appropriate
- [ ] Internationalised: All user facing text
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# Compose URLs
If Build CI hasn't passed, these may 404:

* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9117-fix-users-ddoc-setting/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9117-fix-users-ddoc-setting/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9117-fix-users-ddoc-setting/docker-compose/cht-couchdb-clustered.yml)

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

### CODE REVIEW

**Review by garethbowen — APPROVED** [review]
Thank you!

**Comment by dianabarsan** [comment]
> I'm also noticing the admin user gets logged out after the upgrade, but other users are not. It would be useful to confirm whether this behavior is also observed during your testing @lorerod . I'm looking into it already.

Not relevant. My local install was reusing an existent and malformed credentials volume (which i had created a while ago to demonstrate this behavior)

**Review by m5r — APPROVED** [review]
Tested locally using cht docker helper, I replicated the bug on an instance running 4.7.0 and managed to upgrade properly another instance running this branch. LGTM!

**Comment by mrjones-plip** [comment]
Noting that @lorerod is out of office today and tomorrow ( May 14 & 15)

**Comment by garethbowen** [comment]
Merged. Thank you @m5r and @dianabarsan !

**Pull request merged**
