### PR TITLE
chore(#8459): update nginx image to latest 1.x

### PR DESCRIPTION
**Pull request by mrjones-plip**
# Description

bump nginx image version to latest `1.x`

medic/cht-core#8459

### testing

* checkout this branch
* `cd cht-core/nginx` 
* build new image for nginx: `docker build -t 8459-nginx-bump .`
* start a new docker helper instance `8459_nginx_bump`
* change compose file to have nginx service use new image  `~/.medic/cht-docker/8459_nginx_bump-dir/compose/cht-core.yml` **_OR_** download the core-compose file from this PR - you pick!
* restart cht instance and check all is well poking around on a browser and on mobile device running CHT Android 1.x
* use `curl` to validate `nginx` is at `1.25.1`:
   ```
   curl -s -o /dev/null -v https://192-168-1-132.local-ip.medicmobile.org:10450  2>&1 | grep -i Server:
   < Server: nginx/1.25.1
   ```

# Code review checklist

- [X] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- [X] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# Compose URLs

If Build CI hasn't passed, these may 404:

* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8459-bump-nginx/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8459-bump-nginx/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8459-bump-nginx/docker-compose/cht-couchdb-clustered.yml)

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

### CODE REVIEW

**Review by nydr — APPROVED** [review]
LGTM 👍  Thanks for taking the initiative!

**Comment by mrjones-plip** [comment]
@garethbowen  - next steps?  A quick round of QA or ship it?

**Comment by garethbowen** [comment]
@mrjones-plip It'll need a rebase to get the build to go green. Otherwise, I'm not sure what has been tested already. Testing on an actual server (instead of localhost) might be good?

PS: How's the jetlag?

**Comment by mrjones-plip** [comment]
> Otherwise, I'm not sure what has been tested already. Testing on an actual server (instead of localhost) might be good?

Testing steps I took are [here](https://github.com/medic/cht-core/pull/8460#issue-1850083835),  but tl;dr - build an image and test it with valid TLS via docker helper.

**Comment by mrjones-plip** [comment]
Updating the ticket to confirm passing smoke tests from:
* firefox latest on ubuntu
* chrome latest on ubuntu
* chrome 95 on android 5.1 webview 95
* cht android 1.x on android 5.1 webview 95

I [asked QA to spot check](https://medic.slack.com/archives/CBDHSGQ8L/p1693341275201569) if they feel it's warranted.

**Comment by tatilepizs** [comment]
I just tested it using a docker helper instance and it worked perfectly. Thank you @mrjones-plip for the steps in the description, they were really easy to follow ✨ 

image

image

**Comment by mrjones-plip** [comment]
thanks @tatilepizs

**Pull request merged**
