### PR TITLE
Updated eslint rules

### PR DESCRIPTION
**Pull request by dianabarsan**
# Description

Eslint rules PRs will be merged into this branch. 

medic/cht-core#7440

# Code review checklist

- [ ] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- [ ] Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- [ ] Tested: Unit and/or e2e where appropriate
- [ ] Internationalised: All user facing text
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

### CODE REVIEW

**Comment by garethbowen** [comment]
@dianabarsan Is it worth getting this merged soon and then continuing with other eslint rules in a separate PR? I worry about it getting out of date and then conflicting too much!

**Comment by dianabarsan** [comment]
I have one more branch in progress. I'll try to attend to that this week, get it merged to this one and then we can proceed with this.

**Comment by dianabarsan** [comment]
I merged that last branch in progress and prepped this one to be up to date with `master`. 
Can I get an OK?

**Review by garethbowen — APPROVED** [review]
Awesome. Merge it quick!

**Pull request merged**
