### PR TITLE
Standalone admin

### PR DESCRIPTION
**Pull request by dianabarsan**
# Description

Duplicates and moves files that admin required from webapp. 
This PR must be commit merged into `master` to preserve the duplicated history. 

medic/cht-core#6616

# Code review items

- Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- Tested: Unit and/or e2e where appropriate
- Internationalised: All user facing text
- Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

### CODE REVIEW

**Comment by dianabarsan** [comment]
@garethbowen here it is. Please have a look. Thanks!

**Review by garethbowen — APPROVED** [review]
Awesome.

**Comment by garethbowen** [comment]
@dianabarsan I think this also means we can improve our watchers so changes in webapp don't have to build and publish admin, right?

**Comment by dianabarsan** [comment]
Yeah ... :( I completely forgot about that. Do you think I should redo-it?

**Comment by garethbowen** [comment]
Nah, it's fine to update the grunt file separately.

**Pull request merged**
