### PR TITLE
Export action e2e tests

### PR DESCRIPTION
**Pull request by latin-panda**
# Description

- Adds e2e tests to Export action in Messages, Reports and Contacts tabs.
- Stabilises message page object to reduce flaky tests occurrences.
- Adds reusable utils to work with the download of files

#7872 

# Code review checklist

- [ ] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- [ ] Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- [ ] Tested: Unit and/or e2e where appropriate
- [ ] Internationalised: All user facing text
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# Compose URLs

If Build CI hasn't passed, these may 404:

* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:export-action-e2e/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:export-action-e2e/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:export-action-e2e/docker-compose/cht-couchdb-clustered.yml)
 
# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

### CODE REVIEW

**Comment by latin-panda** [comment]
Hi @lorerod @ngaruko @tatilepizs I think I'm at a good point for feedback, what do you think about this approach? I tried to make it as minimal as possible and reusable.
Thank you for your time!

**Review by tatilepizs — APPROVED** [review]
It looks really good to me Jenny 🎉 
I even learned from this PR, thanks!

**Comment by latin-panda** [comment]
@tatilepizs @lorerod @ngaruko I've included one more test for the Export of messages. 
Also, I've fixed a bit the message page object to increase stability, hopefully we see the breadcrumbs flaky test failing less.

This PR is ready for another review, I don't think I'll be pushing more changes for now.
Thanks!

**Review by tatilepizs — APPROVED** [review]
The export of messages test also looks ready good.
Thank you for adding all of those `waitForClickable` in the messages page-object, I am sure it will help also to other e2e tests ✨

**Review by lorerod — APPROVED** [review]
OMG, @latin-panda, this looks great! Really! Easy to understand. At one point, I thought on suggesting to make general utils for contacts, reports, and sms. But it is better this way because we don't lose clarity.

**Comment by latin-panda** [comment]
@lorerod @ngaruko @tatilepizs Thank you for the review! 
Bede, the seeding data sounds interesting, looking forward to it! 

Happy holidays!

**Pull request merged**
