### PR TITLE
Updates Webapp to use Angular 10

### PR DESCRIPTION
**Pull request by dianabarsan**
# Description

https://github.com/medic/cht-core/issues/4750

# Code review checklist

- [ ] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- [ ] Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- [ ] Tested: Unit and/or e2e where appropriate
- [ ] Internationalised: All user facing text
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

### CODE REVIEW

**Comment by dianabarsan** [comment]
I've tested the merge on my fork: https://github.com/dianabarsan/cht-core and code ownership was preserved successfully.

**Comment by dianabarsan** [comment]
@newtewt I would very much appreciate if you'd give this a sanity check (pull and build locally) before I commit to having people stream through 86,505 lines of code, please. Thanks in advance!

**Comment by dianabarsan** [comment]
A question for the crowd: on the angular migration branch, we had removed travis.yml, and I merged that change into this PR (which consequently generates the two Travis failures). 

Do we want to continue on GHA or stick to Travis?

**Comment by newtewt** [comment]
@dianabarsan  I cloned cht-core to a separate dir and ran through the process of getting up and running from scratch. As far as I can tell that process works fine. I also did an updgrade on my docker version 3.10 to `take-4` and it seemed to work fine as well.

**Comment by dianabarsan** [comment]
Thanks a lot @newtewt .

**Comment by garethbowen** [comment]
I've turned off the travis check requirement so this won't block the merge.

**Comment by dianabarsan** [comment]
Anybody volunteering for a review? The last 2 commits are merge and build fixes post rebase, everything else is cherry-picked from `4750-angular-10-take-2`

**Review by craig-landry — APPROVED** [review]
Have you considered using the [ngMigration Assistant](https://blog.angular.io/migrating-to-angular-fc9618d6fb04) instead?  ;)

**Pull request merged**
