### PR TITLE
chore(#8214): Increase nginx timeout to 1h to match ALB timeout

### PR DESCRIPTION
**Pull request by dianabarsan**
# Description

medic/cht-core#8214

# Code review checklist

- [ ] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- [ ] Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- [ ] Tested: Unit and/or e2e where appropriate
- [ ] Internationalised: All user facing text
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# Compose URLs

If Build CI hasn't passed, these may 404:

* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8214-increase-nginx-timout/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8214-increase-nginx-timout/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8214-increase-nginx-timout/docker-compose/cht-couchdb-clustered.yml)

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

### CODE REVIEW

**Comment by kennsippell** [comment]
I believe both MoH Kenya and MoH Uganda are self-hosting behind nginx and this could be quite relevant for them (?) Is it reasonable to get this into a 4.2.1?

**Review by henokgetachew — APPROVED** [review]
LGTM

**Comment by dianabarsan** [comment]
I think it's completely reasonable @kennsippell . i believe both instances are now on 3.x (except for their training instances)? is that correct? im trying to assess the urgency of this. 
we want to get 4.3 out as soon as possible with the replication improvements - updated algo and "infinite" purge cache.

**Comment by derickl** [comment]
For Kenya, only production is yet to go to 4.x and this will be really soon. In the next week or two. It would be helpful to have consistent environments (to the greatest degree possible) between self-hosters and our set up.

**Comment by dianabarsan** [comment]
Thanks for the input @derickl . I'll follow up on this next week (i'm off for the rest of the week). Theoretically there should be little effort to release this in 4.2.1.

**Pull request merged**
