### PR TITLE
chore(#8087): Flaky test: Submit Default Delivery Report open, submit and edit default delivery form

### PR DESCRIPTION
**Pull request by ngaruko**
# Description

[description]

medic/cht-core #8087 

# Code review checklist

- [ ] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- [ ] Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- [ ] Tested: Unit and/or e2e where appropriate
- [ ] Internationalised: All user facing text
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# Compose URLs

If Build CI hasn't passed, these may 404:

* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8087-flaky-test-default-pregnancy-form/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8087-flaky-test-default-pregnancy-form/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8087-flaky-test-default-pregnancy-form/docker-compose/cht-couchdb-clustered.yml)

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

### CODE REVIEW

**Comment by garethbowen** [comment]
@lorerod Would you be able to take a look at this please? It may just need a review or may need some additional changes.

**Comment by garethbowen** [comment]
@lorerod Did you get a chance to look at this?

**Comment by lorerod** [comment]
@garethbowen reviewing [chore(#8701): Clean and organize e2e tests: folder /enketo](https://github.com/medic/cht-core/pull/8812#top) PR I came across [this](https://github.com/medic/cht-core/pull/8812/commits/0c34a50669811a064d183cea08723fb13cb36dd2) commit where the spec file is deleted and the scenarios were included in `pregnancy-complete-a-delivery` test. After finishing the review and ensuring the scenarios are included, I will close this PR and the issue.

**Comment by lorerod** [comment]
I will close this PR as the issue was addressed in [chore(#8701): Clean and organize e2e tests: folder /enketo](https://github.com/medic/cht-core/pull/8812#top)

**Pull request closed without merging**
