### PR TITLE
New Maternal, Newborn and Child Health reference app

### PR DESCRIPTION
**Pull request by mrjones-plip**
# Description

Holding place for future Maternal, Newborn and Child Health (MNCH) app 

medic/cht-core#6727

# Code review items

- Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- Tested: Unit and/or e2e where appropriate
- Internationalised: All user facing text
- Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

### CODE REVIEW

**Comment by mrjones-plip** [comment]
@Marina-Kenf  - Do you have free moment to look at how I'm progressing on the tasks for this MNCH PR? I'd love to get some feedback early next week.

I'm mainly worried about when two tasks need to be created one due in 3 days and one in 6 days.  I've done this by having this [task for 3 days](https://github.com/medic/cht-core/blob/3920a3b753451a89461951adfb6663126c386ed4/config/default/tasks.js#L203) and [this one for 6 days](https://github.com/medic/cht-core/blob/3920a3b753451a89461951adfb6663126c386ed4/config/default/tasks.js#L296).  These are defined based off the original [design doc here](https://docs.google.com/spreadsheets/d/1_V7tQsH5fO08PAOdfOUPElsSZVfMQO0vx7XLQqYizZ0/edit#gid=0).

What concerns me specifically, is that I'd expect both the 3 day and the 6 day task to show up in the CHT after I fill out the form which generates these to tasks. However, I only ever see one.  You can see in my deep links above, but for quick reference, I've declared the 3 day task as:

```node
events: [
  {
    id: 'child_referral_follow_up_3day',
    days: 3, start: 3, end: 3
  }
]
```

And then then 6 day task as: 

```node
events: [
  {
    id: 'child_referral_follow_up_6day',
    days: 6, start: 3, end: 3
  }
]
```

I was kinda asking about this [in #app-services here](https://medic.slack.com/archives/C0813CQRX/p1611875062024600), but was confused  :stuck_out_tongue_winking_eye: . But now I'm confused again in the same way and thought your expertise could assist me!

**Comment by Marina-Kenf** [comment]
@mrjones-plip - sorry for the delay of my reply - what controls the moment you want the task to show-up it's the `start`. 
So If your task due date is `x` then you want it to show immediately after you've filled the form, your `start` should be `x-day` before the due date that is `x`.
For your above code, I believe it's the 3-day task that is showing up because your start is correct.

Could you please try this for the 6 day task?

```
events: [
  {
    id: 'child_referral_follow_up_6day',
    days: 6, start: 6, end: 3
  }
]

```

**Comment by Marina-Kenf** [comment]
Also, it looks like the 2 tasks are triggered by the same thing and have the same action form? 
If it's the case, it might be better to have a single code for the task and using an array of events for day-3 and day-6.

**Comment by mrjones-plip** [comment]
The larger rollout of the MNCH app has been stalled for over 8 months. I'm going to close all the tickets and PRs. If we want to re-open them to work on this again, all good!

**Pull request closed without merging**
