### PR TITLE
Support node 16

### PR DESCRIPTION
**Pull request by dianabarsan**
# Description

Drop support for Node 8, 10, 12. 
Now only support Node 16 & npm 8+ (needed for the local libraries linking correctly). 
Updates all `package-lock.json` files to version 2. 
Also drop all dev dependencies from shared-libs and all apps and move them to the root package.json. 
Update Admin, API, Sentinel and Webapp so npm handles symlinks to shared-libs (no more copying or linking at build time). 

medic/cht-core#7393

# Code review checklist

- [ ] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- [ ] Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- [ ] Tested: Unit and/or e2e where appropriate
- [ ] Internationalised: All user facing text
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

### CODE REVIEW

**Comment by dianabarsan** [comment]
Hey @latin-panda . Would you mind reviewing this? 
I know the change count looks scary, but 99% are just package-lock json edits, moving from version 1 to version 2. 
It would be really useful to see if this also works correctly in OSX. 

Thanks a lot for your time! 

Oh, one note! 
I didn't go over all the changes that we can make now that we have Node 16, I just went over code that's been added in the CHT 4.0 arch v3 batch.

**Review by latin-panda — COMMENTED** [review]
Nice, I can't wait to have node 16 available for work! Later we can remove some support code that target older versions, to simplify.  

Is the `lockfileVersion` remain `1` for the `package-lock.json` files in `/config/**`, `/script/**`, `/suport-script/**` and `/tests/scalability/**` ?

Also, are we going to keep the `package.json`'s `devDependencies`  for `/config/**`, `/script/**`?

Do you get this warning with Angular dependencies? However looks to work fine, I tested with online and offline users. 
```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@angular-devkit/core@12.2.1',
npm WARN EBADENGINE   required: {
npm WARN EBADENGINE     node: '^12.14.1 || >=14.0.0',
npm WARN EBADENGINE     npm: '^6.11.0 || ^7.5.6',
npm WARN EBADENGINE     yarn: '>= 1.13.0'
npm WARN EBADENGINE   },
npm WARN EBADENGINE   current: { node: 'v16.14.0', npm: '8.3.1' }
npm WARN EBADENGINE }
```

**Comment by latin-panda** [comment]
Quick question about cht-core v4, are we going to upgrade dependencies? I remember we couldn't upgrade some because they dropped the node versions we supported. Like Sinon, Karma-firefox-launcher, helmet, etc.

**Comment by dianabarsan** [comment]
> Is the lockfileVersion remain 1 for the package-lock.json files in /config/**, /script/**, /suport-script/** and /tests/scalability/** ?

I didn't want to touch `config` or `script` at all in this iteration. I wanted to keep this branch as slim as possible with just what is absolutely needed. 
We should definitely do all of those at some point, before releasing 4.0.

> Do you get this warning with Angular dependencies?

Yea, it's because of the `npm` version:  `npm: '^6.11.0 || ^7.5.6'`. I didn't, however, find any reference of this in their codebase (so I think it's some build-time artifact). 
The current `package.json` says to exclusively use `yarn`: https://github.com/angular/angular-cli/blob/master/package.json#L45

Also, we're running Angular 12. Angular 13 has been released and the engines section has changed:  
```
"engines": {
    "node": "^12.20.0 || ^14.15.0 || >=16.10.0",
    "npm": "^6.11.0 || ^7.5.6 || >=8.0.0",
    "yarn": ">= 1.13.0"
  },
```

So I'm not really worried about it.

**Comment by dianabarsan** [comment]
> Quick question about cht-core v4, are we going to upgrade dependencies?

Absolutely. Though I don't think we should do that until we branch off 3.15 and work on latest, because It would be a lot of work to rebase.

**Review by latin-panda — APPROVED** [review]
Sounds good!

**Pull request merged**
