### PR TITLE
Adds translations exported from POE

### PR DESCRIPTION
**Pull request by dianabarsan**
# Description

medic/cht-core#6418

# Code review items

- Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- Tested: Unit and/or e2e where appropriate
- Internationalised: All user facing text
- Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

### CODE REVIEW

**Review by garethbowen — APPROVED** [review]
LGTM!

**Comment by mrsarm** [comment]
Hey @dianabarsan , I did update a lot of Spanish translations from POEeditor.com last month, many of the translations I fixed were wrong (like translated with Google Translate) and I added all the missed keys used in the UI for basic usages, like some missed translations from the form to change the user password. Could you add them in the PR?

I know that currently we don't have deployments using Spanish, but it would be useful if in the future are needed, specially to make a demo.

**Comment by garethbowen** [comment]
Yeah, good point! Where are those additional translation files?? Thanks for pointing that out @mrsarm

**Review by garethbowen — CHANGES_REQUESTED** [review]
It looks like some files are missing, eg: "es"?

**Comment by garethbowen** [comment]
I've exported and added es, ne, and sw that were missed originally.

**Review by garethbowen — APPROVED** [review]

**Comment by dianabarsan** [comment]
So sorry, I have no idea what happened there. :(

**Pull request merged**
