### PR TITLE
fix(#8582): fixes http2 declaration warning

### PR DESCRIPTION
**Pull request by mrjones-plip**
# fixes http2 declaration warning 

close medic/cht-core#8582

# Code review checklist

- [X] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- [X] Tested: Unit and/or e2e where appropriate
- [X] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# Compose URLs

If Build CI hasn't passed, these may 404:

* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8582-tidy-up-http2-warning/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8582-tidy-up-http2-warning/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8582-tidy-up-http2-warning/docker-compose/cht-couchdb-clustered.yml)

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

### CODE REVIEW

**Comment by mrjones-plip** [comment]
How to test:
* check out this branch
* deploy CHT4 with [docker helper](https://docs.communityhealthtoolkit.org/apps/guides/hosting/4.x/app-developer/#cht-docker-helper-for-4x)
* check with `curl` that CHT defaults to http2, can be forced to  http2 and can fall back to http1.1:
   ```
   curl  -sI  https://CHT_URL:CHT_PORT/  -o/dev/null -w '%{http_version}\n' 
   curl --http2 -sI  https://CHT_URL:CHT_PORT  -o/dev/null -w '%{http_version}\n' 
   curl --http1.1 -sI  https://CHT_URL:CHT_PORT/  -o/dev/null -w '%{http_version}\n' 
   ```
* find `nginx` container name: ` docker ps --format '{{.Names}}'|grep nginx`
* assuming your container is called `4_4_test_nginx_1`, copy in updated config: `docker exec -it 4_4_test_nginx_1 /usr/sbin/nginx  -s reload`
* recheck with `curl` that CHT defaults to http2, can be forced to  http2 and can fall back to http1.1:
   ```
   curl  -sI  https://CHT_URL:CHT_PORT/  -o/dev/null -w '%{http_version}\n' 
   curl --http2 -sI  https://CHT_URL:CHT_PORT  -o/dev/null -w '%{http_version}\n' 
   curl --http1.1 -sI  https://CHT_URL:CHT_PORT/  -o/dev/null -w '%{http_version}\n' 
   ```
* restart container and check with `docker logs CONTAINER_NAME` that the warning isn't there: `warn] the "listen ... http2" directive is deprecated`

**Review by nydr — APPROVED** [review]
LGTM, love that you're paying attention to these details!

Sidenote: *This directive was introduced in `1.25.1` [[ref](https://nginx.org/en/docs/http/ngx_http_v2_module.html#http2)] which the nginx container was upgraded to a few months ago. Since the configuration is packaged with the binary I can't imagine it can cause any issues but noting this just in case*

**Comment by nydr** [comment]
Optional: If you feel up for it feel free to add your test cases to `nginx/tests/with_mock.bats`

**Comment by mrjones-plip** [comment]
> Optional: If you feel up for it feel free to add your test cases to nginx/tests/with_mock.bats, currently it's only looking at http headers

d'oh -   Missed opportunity here!  I should have said "Run Makefile tests" as you already had tests in there [for](https://github.com/medic/cht-core/blob/242d18486804502cfc82d1f1b4b0a73fbb342e54/nginx/tests/with_mock.bats#L39) `http1.1` and `http2` [checks](https://github.com/medic/cht-core/blob/242d18486804502cfc82d1f1b4b0a73fbb342e54/nginx/tests/with_mock.bats#L45).  That said, I skipped adding more because what we have is sufficient.

**Pull request merged**
